"use client";
import { useLocale } from "@/lib/i18n";
export const editorCopy = {
  "ru": {
    "promptEdit": "Монтаж по промпту",
    "promptHint": "Например: «Вертикальный 9:16, обрежь с 2 до 12 секунд, заголовок “Наш продукт”, логотип справа сверху».",
    "prepare": "Предложить изменения",
    "apply": "Применить монтаж",
    "undo": "Отменить изменения",
    "working": "Обрабатывается…",
    "changes": "Изменения монтажа",
    "local": "Команды распознаны локально",
    "ai": "Предложение Owner AI",
    "autoCaptions": "Распознать речь и добавить субтитры",
    "generationNote": "Создайте медиа здесь и добавьте результат на таймлайн.",
    "generate": "Сгенерировать медиа",
    "addTimeline": "Добавить на таймлайн",
    "replaceNote": "Видео и изображения заменяют основной клип; музыка и голос добавляются отдельными дорожками.",
    "providerMissing": "Для этого действия подключите медиапровайдер в настройках сервера.",
    "providerFailure": "Провайдер не выполнил запрос. Попробуйте ещё раз.",
    "failure": "Не удалось выполнить действие.",
    "fileTooLarge": "Файл должен быть не больше 4 МБ. Для транскрипции выберите более короткий фрагмент.",
    "invalidFile": "Выберите поддерживаемый файл.",
    "unsupportedPrompt": "Команда не распознана. Укажите формат, границы обрезки, текст, эффект или положение логотипа.",
    "invalidTrim": "Начало должно быть раньше конца, а фрагмент — внутри загруженного медиа.",
    "subtitleInvalid": "Не удалось прочитать субтитры. Проверьте SRT/VTT и таймкоды.",
    "transcriptEmpty": "Провайдер не вернул распознанный текст.",
    "referenceRequired": "Добавьте фото для создания аватара.",
    "source": "Источник речи",
    "mainSource": "Основное видео / аудио",
    "musicSource": "Аудиодорожка",
    "voiceSource": "Озвучка",
    "detectLanguage": "Определить язык",
    "transcribe": "Транскрибировать",
    "transcript": "Транскрипция",
    "downloadText": "Скачать текст",
    "importCaptions": "Импорт SRT / VTT",
    "addCue": "Добавить субтитр",
    "deleteCue": "Удалить субтитр",
    "cueText": "Текст субтитра",
    "cueStart": "Начало, с",
    "cueEnd": "Конец, с",
    "timedCaptions": "Субтитры по таймкодам",
    "noCues": "Добавьте субтитр вручную, импортируйте SRT/VTT или распознайте речь.",
    "noTimes": "Текст распознан без таймкодов. Импортируйте SRT/VTT или добавьте субтитры вручную.",
    "srt": "Скачать SRT",
    "vtt": "Скачать VTT",
    "logoUpload": "Загрузить логотип",
    "logoRemove": "Убрать логотип",
    "logoPosition": "Положение логотипа",
    "logoSize": "Размер логотипа",
    "logoOpacity": "Прозрачность логотипа",
    "logoCorners": [
      "Слева сверху",
      "Справа сверху",
      "Слева снизу",
      "Справа снизу"
    ],
    "logoNote": "PNG, JPEG или WebP, до 4 МБ. PNG сохраняет прозрачный фон.",
    "render": "Экспорт монтажа · WebM",
    "rendering": "Рендерится…",
    "renderNote": "Экспорт WebM включает обрезку, текст, субтитры, логотип, эффекты и аудиодорожки. Рендер идёт в реальном времени; держите страницу открытой.",
    "renderUnsupported": "Этот браузер не поддерживает экспорт WebM.",
    "cancel": "Отмена",
    "reference": "Фото / изображение-референс",
    "voice": "Голос",
    "duration": "Длительность, с",
    "original": "Скачать исходник",
    "subtitleStatic": "Постоянная подпись",
    "transcribeNote": "Видео или аудио отправляется подключённому сервису распознавания речи.",
    "mediaRequired": "Сначала добавьте видео или аудио.",
    "imageDuration": "Длительность изображения",
    "generationFailed": "Не удалось загрузить результат генерации.",
    "logo": "Логотип"
  },
  "en": {
    "promptEdit": "Edit with a prompt",
    "promptHint": "For example: “Vertical 9:16, trim from 2 to 12 seconds, title ‘Our product’, logo at the top right”.",
    "prepare": "Propose changes",
    "apply": "Apply edit",
    "undo": "Undo changes",
    "working": "Processing…",
    "changes": "Editing changes",
    "local": "Commands recognized locally",
    "ai": "Owner AI proposal",
    "autoCaptions": "Transcribe speech and add captions",
    "generationNote": "Create media here and add the result to the timeline.",
    "generate": "Generate media",
    "addTimeline": "Add to timeline",
    "replaceNote": "Video and images replace the main clip; music and voice are added as separate tracks.",
    "providerMissing": "Connect a media provider in the server settings to use this action.",
    "providerFailure": "The provider could not complete the request. Please retry.",
    "failure": "The action could not be completed.",
    "fileTooLarge": "The file must be 4 MB or smaller. Choose a shorter excerpt for transcription.",
    "invalidFile": "Choose a supported file.",
    "unsupportedPrompt": "Command not recognized. Specify a format, trim range, text, effect, or logo position.",
    "invalidTrim": "Start must precede end and the excerpt must stay inside the loaded media.",
    "subtitleInvalid": "Could not read captions. Check the SRT/VTT format and timestamps.",
    "transcriptEmpty": "The provider returned no transcript.",
    "referenceRequired": "Add a photo to create an avatar.",
    "source": "Speech source",
    "mainSource": "Main video / audio",
    "musicSource": "Audio track",
    "voiceSource": "Voiceover",
    "detectLanguage": "Detect language",
    "transcribe": "Transcribe",
    "transcript": "Transcript",
    "downloadText": "Download text",
    "importCaptions": "Import SRT / VTT",
    "addCue": "Add caption",
    "deleteCue": "Delete caption",
    "cueText": "Caption text",
    "cueStart": "Start, s",
    "cueEnd": "End, s",
    "timedCaptions": "Timed captions",
    "noCues": "Add a caption, import SRT/VTT, or transcribe speech.",
    "noTimes": "Speech was transcribed without timestamps. Import SRT/VTT or add captions manually.",
    "srt": "Download SRT",
    "vtt": "Download VTT",
    "logoUpload": "Upload logo",
    "logoRemove": "Remove logo",
    "logoPosition": "Logo position",
    "logoSize": "Logo size",
    "logoOpacity": "Logo opacity",
    "logoCorners": [
      "Top left",
      "Top right",
      "Bottom left",
      "Bottom right"
    ],
    "logoNote": "PNG, JPEG or WebP, up to 4 MB. PNG preserves transparency.",
    "render": "Export montage · WebM",
    "rendering": "Rendering…",
    "renderNote": "WebM export includes trimming, text, captions, logo, effects and audio tracks. Rendering takes real time; keep this page open.",
    "renderUnsupported": "This browser does not support WebM export.",
    "cancel": "Cancel",
    "reference": "Reference photo / image",
    "voice": "Voice",
    "duration": "Duration, s",
    "original": "Download source",
    "subtitleStatic": "Persistent caption",
    "transcribeNote": "Your video or audio is sent to the connected speech recognition service.",
    "mediaRequired": "Add video or audio first.",
    "imageDuration": "Image duration",
    "generationFailed": "Could not load the generated media.",
    "logo": "Logo"
  },
  "hy": {
    "promptEdit": "Մոնտաժ՝ տեքստային հրահանգով",
    "promptHint": "Օրինակ՝ «Ուղղահայաց 9:16, կտրիր 2-ից մինչև 12 վայրկյանը, վերնագիր՝ “Մեր ապրանքը”, լոգոն՝ աջ վերևում»։",
    "prepare": "Առաջարկել փոփոխություններ",
    "apply": "Կիրառել մոնտաժը",
    "undo": "Չեղարկել փոփոխությունները",
    "working": "Մշակվում է…",
    "changes": "Մոնտաժի փոփոխություններ",
    "local": "Հրահանգները ճանաչվել են տեղում",
    "ai": "Owner AI-ի առաջարկը",
    "autoCaptions": "Վերծանել խոսքը և ավելացնել ենթագրեր",
    "generationNote": "Ստեղծեք մեդիա այստեղ և արդյունքն ավելացրեք ժամանակագծին։",
    "generate": "Գեներացնել մեդիա",
    "addTimeline": "Ավելացնել ժամանակագծին",
    "replaceNote": "Տեսանյութերն ու պատկերները փոխարինում են հիմնական հոլովակը, իսկ երաժշտությունն ու ձայնը ավելանում են առանձին թրեքերով։",
    "providerMissing": "Այս գործողության համար սերվերի կարգավորումներում միացրեք մեդիա ծառայություն։",
    "providerFailure": "Ծառայությունը չի կատարել հարցումը։ Փորձեք կրկին։",
    "failure": "Չհաջողվեց կատարել գործողությունը։",
    "fileTooLarge": "Ֆայլը պետք է լինի առավելագույնը 4 ՄԲ։ Վերծանման համար ընտրեք ավելի կարճ հատված։",
    "invalidFile": "Ընտրեք աջակցվող ֆայլ։",
    "unsupportedPrompt": "Հրահանգը չի ճանաչվել։ Նշեք ձևաչափը, կտրման սահմանները, տեքստը, էֆեկտը կամ լոգոյի դիրքը։",
    "invalidTrim": "Սկիզբը պետք է լինի ավարտից առաջ, իսկ հատվածը՝ բեռնված մեդիայի սահմաններում։",
    "subtitleInvalid": "Չհաջողվեց կարդալ ենթագրերը։ Ստուգեք SRT/VTT ձևաչափն ու ժամանակները։",
    "transcriptEmpty": "Ծառայությունը չի վերադարձրել վերծանված տեքստ։",
    "referenceRequired": "Ավատար ստեղծելու համար ավելացրեք լուսանկար։",
    "source": "Խոսքի աղբյուր",
    "mainSource": "Հիմնական տեսանյութ / աուդիո",
    "musicSource": "Աուդիո թրեք",
    "voiceSource": "Ձայնավորում",
    "detectLanguage": "Որոշել լեզուն",
    "transcribe": "Վերծանել",
    "transcript": "Վերծանված տեքստ",
    "downloadText": "Ներբեռնել տեքստը",
    "importCaptions": "Ներմուծել SRT / VTT",
    "addCue": "Ավելացնել ենթագիր",
    "deleteCue": "Ջնջել ենթագիրը",
    "cueText": "Ենթագրի տեքստ",
    "cueStart": "Սկիզբ, վ",
    "cueEnd": "Ավարտ, վ",
    "timedCaptions": "Ենթագրեր՝ ժամանակային նշումներով",
    "noCues": "Ավելացրեք ենթագիր, ներմուծեք SRT/VTT կամ վերծանեք խոսքը։",
    "noTimes": "Խոսքը վերծանվել է առանց ժամանակային նշումների։ Ներմուծեք SRT/VTT կամ ավելացրեք ենթագրերը ձեռքով։",
    "srt": "Ներբեռնել SRT",
    "vtt": "Ներբեռնել VTT",
    "logoUpload": "Բեռնել լոգոն",
    "logoRemove": "Հեռացնել լոգոն",
    "logoPosition": "Լոգոյի դիրքը",
    "logoSize": "Լոգոյի չափը",
    "logoOpacity": "Լոգոյի թափանցիկությունը",
    "logoCorners": [
      "Ձախ վերևում",
      "Աջ վերևում",
      "Ձախ ներքևում",
      "Աջ ներքևում"
    ],
    "logoNote": "PNG, JPEG կամ WebP՝ մինչև 4 ՄԲ։ PNG-ը պահպանում է թափանցիկ ֆոնը։",
    "render": "Արտահանել մոնտաժը · WebM",
    "rendering": "Արտապատկերվում է…",
    "renderNote": "WebM արտահանումը ներառում է կտրումը, տեքստը, ենթագրերը, լոգոն, էֆեկտներն ու աուդիո թրեքերը։ Արտապատկերումը կատարվում է իրական ժամանակում․ էջը բաց պահեք։",
    "renderUnsupported": "Այս զննարկիչը չի աջակցում WebM արտահանմանը։",
    "cancel": "Չեղարկել",
    "reference": "Հղումային լուսանկար / պատկեր",
    "voice": "Ձայն",
    "duration": "Տևողություն, վ",
    "original": "Ներբեռնել սկզբնական ֆայլը",
    "subtitleStatic": "Մշտական գրություն",
    "transcribeNote": "Ձեր տեսանյութը կամ աուդիոն ուղարկվում է խոսքի ճանաչման միացված ծառայությանը։",
    "mediaRequired": "Նախ ավելացրեք տեսանյութ կամ աուդիո։",
    "imageDuration": "Պատկերի տևողությունը",
    "generationFailed": "Չհաջողվեց բեռնել գեներացված մեդիան։",
    "logo": "Լոգո"
  }
};
export function useEditorCopy() { const { locale } = useLocale(); return editorCopy[locale]; }
export type EditorCopy = typeof editorCopy.en;
export function studioError(error: unknown, copy: EditorCopy): string {
 const code = error instanceof Error ? error.message : "";
 const messages: Record<string,string> = { STUDIO_PROVIDER_NOT_CONFIGURED:copy.providerMissing, STUDIO_PROVIDER_UNAVAILABLE:copy.providerFailure, STUDIO_FILE_TOO_LARGE:copy.fileTooLarge, STUDIO_FILE_INVALID:copy.invalidFile, STUDIO_SUBTITLES_INVALID:copy.subtitleInvalid, STUDIO_TRANSCRIPT_EMPTY:copy.transcriptEmpty, STUDIO_PROMPT_UNSUPPORTED:copy.unsupportedPrompt, STUDIO_TRIM_INVALID:copy.invalidTrim, STUDIO_REFERENCE_REQUIRED:copy.referenceRequired, STUDIO_RENDER_UNSUPPORTED:copy.renderUnsupported, STUDIO_MEDIA_REQUIRED:copy.mediaRequired };
 return messages[code] ?? copy.failure;
}
