"use client";

import { useLocale } from "@/lib/i18n";

export const studioCopy = {
  ru: {
    generator: "Генератор контента", generatorNote: "От идеи к видео, звуку, изображению и персонажу.",
    types: ["Видео", "Аудио", "Голос", "Изображение", "Аватар"],
    hints: ["Сценарий и видеоряд", "Музыка и звуковое оформление", "Текст для озвучки", "Сцена и визуальный стиль", "Персонаж и сценарий"],
    open: "Открыть", create: "Создать", prompt: "Описание", placeholder: "Опишите идею, стиль и желаемый результат…",
    format: "Формат", formats: ["Горизонтальный", "Вертикальный", "Квадратный"], style: "Стиль", styles: ["HayDevOS · Стекло и свет", "Кинематографический", "Минималистичный"],
    videoSettingsTabs: ["Настройки", "Стили", "Персонажи", "Звук и язык"],
    videoStyles: ["Кинематографический реализм", "Неон-нуар", "Арт-деко", "Документальный", "Мягкий утренний свет", "Золотой час", "Ночной город", "Океанский бриз", "Футуристичный глянец", "Ретрофутуризм", "Аниме", "Иллюстрация тушью", "Акварель", "Пластилиновая анимация", "Стилизованный 3D", "Бумажная аппликация", "Графический роман", "Минималистичная студия", "Архитектурная визуализация", "Природная съёмка", "Спортивная динамика", "Музыкальный клип", "Fashion-глянец", "Ностальгия 90-х", "VHS-кассета", "Монохром", "Яркий pop-art", "Мистический туман", "Космическая опера", "Тёплая семейная сцена"],
    soundStyles: ["Кинематографический саундтрек", "Лоу-фай", "Эмбиент", "Электронный", "Оркестровый", "Документальный", "Тёплый акустический", "Тёмный дрон", "Ретро-синтвейв", "Эпический", "Минималистичный", "Без музыки"],
    musicStyles: ["Поп", "Рок", "Инди-поп", "Хип-хоп", "R&B", "Джаз", "Лоу-фай", "Соул", "Фанк", "Диско", "Синтвейв", "Драм-н-бейс", "Хаус", "Техно", "Транс", "Эмбиент", "Классика", "Неоклассика", "Оркестровая баллада", "Акустический фолк", "Кантри", "Регги", "Латина", "Босса-нова", "Блюз", "Панк", "Метал", "К-поп", "Кинематографическая", "Детская песня"],
    languages: ["Русский", "English", "Հայերեն", "Deutsch", "Français", "Español", "中文", "日本語"],
    model: "Модель генерации", modelHint: "Выберите профиль качества и стоимости", modelTiers: { budget: "Доступная", balanced: "Средняя", top: "Топовая" }, duration: "Длительность", durationHint: "Доступные секунды зависят от модели", secondsUnit: "сек.", voiceModel: "Модель голоса", voiceModelHint: "6 профилей: 2 доступных, 2 средних и 2 топовых", voice: "Голос", voiceHint: "Набор голосов зависит от выбранной модели", voiceFemale: "Женский тембр", voiceMale: "Мужской тембр", voiceFormat: "Формат аудио", voiceFormats: ["MP3", "WAV", "Opus"], voiceOfficialNote: "ID голосов взяты из официального OpenAI Audio API. Документация не публикует гендерную метку, поэтому женские и мужские группы — интерфейсная классификация тембра.", voiceDocsLabel: "Открыть официальную документацию TTS",
    frames: "Ключевые кадры", framesHint: "Зафиксируйте начало и конец сцены", firstFrame: "First frame", lastFrame: "Last frame", referencePhoto: "Reference photo", referencePrompt: "Промпт для фото", referencePromptPlaceholder: "Опишите, как использовать это фото в сцене…", noPrompt: "промпт не задан", noFrame: "Кадр не задан", chooseFrame: "Выбрать", replaceFrame: "Заменить",
    stylesHint: "Выберите визуальный язык сцены", audioStyle: "Стиль музыки", audioStylesHint: "Выберите один из 30 музыкальных профилей", audioLanguage: "Язык песни", rhymePolish: "Финальная рифмовка", rhymePolishOn: "ИИ улучшит рифмы и звучание", rhymePolishOff: "Оставить текст без финальной правки", rhymePolishHint: "В конце ИИ сопоставит рифмы, сгладит строки и сделает звучание песни более красивым.", characters: "Персонажи", charactersHint: "Закрепите до трёх персонажей для постоянства между кадрами", characterSlot: "Персонаж {n}", characterName: "Имя", characterDescription: "Описание и внешность", characterNamePlaceholder: "Например: Анна", characterDescriptionPlaceholder: "Лицо, одежда, возраст, характер…", emptyCharacter: "без описания", lock: "Зафиксировать", unlock: "Разблокировать", locked: "зафиксирован", soundStyle: "Стиль звука", lockSound: "Зафиксировать стиль звука", unlockSound: "Разблокировать стиль звука", soundLocked: "Стиль звука зафиксирован", language: "Язык генерации", preferencesSaved: "Настройки видео сохраняются на этом устройстве и добавляются в задание Owner AI.",
    preview: "Предпросмотр", previewEmpty: "Результат появится после подключения сервиса генерации.",
    mediaUnavailable: "Генерация медиа пока не подключена.", generate: "Запустить генерацию", prepare: "Составить задание с Owner AI", preparing: "Отправка…",
    request: "Подготовь задание для создания {type}. Формат: {format}. Стиль: {style}. Описание: {prompt}",
    editor: "Монтажная", project: "Новый монтаж", back: "Назад", import: "Добавить медиа", download: "Скачать проект", export: "Экспорт видео",
    exportUnavailable: "Экспорт готового видео пока не подключён. Можно скачать настройки проекта.",
    tools: ["Медиа", "Шаблоны", "Текст", "Аудио", "Озвучка", "Субтитры", "Эффекты", "Фильтры", "Бренд", "AI-инструменты"],
    empty: "Добавьте видео, изображение или аудио", local: "Предпросмотр использует выбранный файл на этом устройстве.",
    play: "Воспроизвести", pause: "Пауза", seek: "Позиция воспроизведения", tracks: ["Видео", "Текст", "Аудио"],
    inspector: "Свойства", position: "Положение", scale: "Масштаб", rotation: "Поворот", opacity: "Непрозрачность", color: "Цвет", text: "Текст на экране",
    trimStart: "Начало фрагмента", trimEnd: "Конец фрагмента", seconds: "с", subtitle: "Текст субтитров", brand: "Фирменная подпись", filter: "Фильтр", filters: ["Без фильтра", "Чёрно-белый", "Сепия"],
    audioNote: "Добавьте аудиофайл через «Добавить медиа», чтобы прослушать его.", voiceNote: "Озвучка доступна в генераторе после подключения сервиса.",
    templatesNote: "Выберите формат композиции.", effectsNote: "Настройте масштаб, поворот и прозрачность в свойствах.",
    fileError: "Выберите видео, изображение или аудиофайл.", loadError: "Не удалось открыть файл. Попробуйте другой формат.", clear: "Убрать медиа",
  },
  en: {
    generator: "Content generator", generatorNote: "From an idea to video, sound, images and characters.",
    types: ["Video", "Audio", "Voice", "Image", "Avatar"],
    hints: ["Script and visuals", "Music and sound design", "Text to speech", "Scene and visual style", "Character and script"],
    open: "Open", create: "Create", prompt: "Description", placeholder: "Describe your idea, style and desired result…",
    format: "Format", formats: ["Landscape", "Portrait", "Square"], style: "Style", styles: ["HayDevOS · Glass and light", "Cinematic", "Minimal"],
    videoSettingsTabs: ["Settings", "Styles", "Characters", "Sound & language"],
    videoStyles: ["Cinematic realism", "Neon noir", "Art deco", "Documentary", "Soft morning light", "Golden hour", "Night city", "Ocean breeze", "Futuristic gloss", "Retro-futurism", "Anime", "Ink illustration", "Watercolor", "Clay animation", "Stylized 3D", "Paper collage", "Graphic novel", "Minimal studio", "Architectural visualization", "Nature documentary", "Sports motion", "Music video", "Fashion editorial", "90s nostalgia", "VHS tape", "Monochrome", "Bright pop art", "Mystic fog", "Space opera", "Warm family scene"],
    soundStyles: ["Cinematic score", "Lo-fi", "Ambient", "Electronic", "Orchestral", "Documentary", "Warm acoustic", "Dark drone", "Retro synthwave", "Epic", "Minimal", "No music"],
    musicStyles: ["Pop", "Rock", "Indie pop", "Hip-hop", "R&B", "Jazz", "Lo-fi", "Soul", "Funk", "Disco", "Synthwave", "Drum & bass", "House", "Techno", "Trance", "Ambient", "Classical", "Neoclassical", "Orchestral ballad", "Acoustic folk", "Country", "Reggae", "Latin", "Bossa nova", "Blues", "Punk", "Metal", "K-pop", "Cinematic", "Children's song"],
    languages: ["Русский", "English", "Հայերեն", "Deutsch", "Français", "Español", "中文", "日本語"],
    model: "Generation model", modelHint: "Choose the quality and cost profile", modelTiers: { budget: "Budget", balanced: "Balanced", top: "Top" }, duration: "Duration", durationHint: "Available seconds depend on the model", secondsUnit: "sec.", voiceModel: "Voice model", voiceModelHint: "6 profiles: 2 budget, 2 balanced and 2 top", voice: "Voice", voiceHint: "Available voices depend on the selected model", voiceFemale: "Feminine timbre", voiceMale: "Masculine timbre", voiceFormat: "Audio format", voiceFormats: ["MP3", "WAV", "Opus"], voiceOfficialNote: "Voice IDs come from the official OpenAI Audio API. The docs do not publish gender labels, so feminine and masculine groups are an interface timbre classification.", voiceDocsLabel: "Open official TTS documentation",
    frames: "Key frames", framesHint: "Pin the beginning and ending of the scene", firstFrame: "First frame", lastFrame: "Last frame", referencePhoto: "Reference photo", referencePrompt: "Photo prompt", referencePromptPlaceholder: "Describe how to use this photo in the scene…", noPrompt: "no prompt", noFrame: "No frame selected", chooseFrame: "Choose", replaceFrame: "Replace",
    stylesHint: "Choose the visual language of the scene", audioStyle: "Music style", audioStylesHint: "Choose one of 30 music profiles", audioLanguage: "Song language", rhymePolish: "Final rhyme pass", rhymePolishOn: "AI will improve rhymes and sound", rhymePolishOff: "Keep the text without a final pass", rhymePolishHint: "At the end, AI matches rhymes, smooths the lines and makes the song sound more beautiful.", characters: "Characters", charactersHint: "Pin up to three characters for consistency across shots", characterSlot: "Character {n}", characterName: "Name", characterDescription: "Description and appearance", characterNamePlaceholder: "For example: Anna", characterDescriptionPlaceholder: "Face, clothes, age, personality…", emptyCharacter: "no description", lock: "Lock", unlock: "Unlock", locked: "locked", soundStyle: "Sound style", lockSound: "Lock sound style", unlockSound: "Unlock sound style", soundLocked: "Sound style locked", language: "Generation language", preferencesSaved: "Video settings are saved on this device and included in the Owner AI brief.",
    preview: "Preview", previewEmpty: "Results will appear when a generation service is connected.",
    mediaUnavailable: "Media generation is not connected yet.", generate: "Start generation", prepare: "Prepare a brief with Owner AI", preparing: "Sending…",
    request: "Prepare a brief to create {type}. Format: {format}. Style: {style}. Description: {prompt}",
    editor: "Editing room", project: "New edit", back: "Back", import: "Add media", download: "Download project", export: "Export video",
    exportUnavailable: "Video export is not connected yet. You can download the project settings.",
    tools: ["Media", "Templates", "Text", "Audio", "Voice", "Subtitles", "Effects", "Filters", "Brand", "AI tools"],
    empty: "Add a video, image or audio file", local: "The preview uses the file selected on this device.",
    play: "Play", pause: "Pause", seek: "Playback position", tracks: ["Video", "Text", "Audio"],
    inspector: "Properties", position: "Position", scale: "Scale", rotation: "Rotation", opacity: "Opacity", color: "Color", text: "On-screen text",
    trimStart: "Clip start", trimEnd: "Clip end", seconds: "s", subtitle: "Subtitle text", brand: "Brand signature", filter: "Filter", filters: ["None", "Grayscale", "Sepia"],
    audioNote: "Use Add media to select and preview an audio file.", voiceNote: "Voice generation becomes available when a service is connected.",
    templatesNote: "Choose the composition format.", effectsNote: "Adjust scale, rotation and opacity in Properties.",
    fileError: "Choose a video, image or audio file.", loadError: "This file could not be opened. Try another format.", clear: "Remove media",
  },
  hy: {
    generator: "Բովանդակության գեներատոր", generatorNote: "Գաղափարից դեպի տեսանյութ, ձայն, պատկեր և կերպար։",
    types: ["Տեսանյութ", "Աուդիո", "Ձայն", "Պատկեր", "Ավատար"],
    hints: ["Սցենար և տեսաշար", "Երաժշտություն և ձայնային ձևավորում", "Տեքստի ձայնավորում", "Տեսարան և տեսողական ոճ", "Կերպար և սցենար"],
    open: "Բացել", create: "Ստեղծել", prompt: "Նկարագրություն", placeholder: "Նկարագրեք գաղափարը, ոճը և ցանկալի արդյունքը…",
    format: "Ձևաչափ", formats: ["Հորիզոնական", "Ուղղահայաց", "Քառակուսի"], style: "Ոճ", styles: ["HayDevOS · Ապակի և լույս", "Կինեմատոգրաֆիկ", "Մինիմալիստական"],
    videoSettingsTabs: ["Կարգավորումներ", "Ոճեր", "Կերպարներ", "Ձայն և լեզու"],
    videoStyles: ["Կինեմատոգրաֆիկ ռեալիզմ", "Նեոնային նուար", "Արտ դեկո", "Փաստագրական", "Փափուկ առավոտյան լույս", "Ոսկե ժամ", "Գիշերային քաղաք", "Օվկիանոսի քամի", "Ֆուտուրիստական փայլ", "Ռետրոֆուտուրիզմ", "Անիմե", "Թանաքային նկարազարդում", "Ջրաներկ", "Պլաստիլինային անիմացիա", "Ոճավորված 3D", "Թղթե կոլաժ", "Գրաֆիկական վեպ", "Մինիմալ ստուդիա", "Ճարտարապետական վիզուալիզացիա", "Բնության նկարահանում", "Սպորտային դինամիկա", "Երաժշտական տեսահոլովակ", "Fashion խմբագրական", "90-ականների նոստալգիա", "VHS ժապավեն", "Մոնոխրոմ", "Վառ pop-art", "Միստիկ մառախուղ", "Տիեզերական օպերա", "Ջերմ ընտանեկան տեսարան"],
    soundStyles: ["Կինեմատոգրաֆիկ սաունդթրեք", "Լոու-ֆայ", "Ամբիենտ", "Էլեկտրոնային", "Օրկեստրային", "Փաստագրական", "Ջերմ ակուստիկ", "Մութ դրոն", "Ռետրո սինթվեյվ", "Էպիկական", "Մինիմալ", "Առանց երաժշտության"],
    musicStyles: ["Փոփ", "Ռոք", "Ինդի փոփ", "Հիփ-հոփ", "R&B", "Ջազ", "Լոու-ֆայ", "Սոուլ", "Ֆանք", "Դիսկո", "Սինթվեյվ", "Դրամ ընդ բեյս", "Հաուս", "Տեխնո", "Տրանս", "Ամբիենտ", "Դասական", "Նեոդասական", "Օրկեստրային բալլադ", "Ակուստիկ ֆոլք", "Քանթրի", "Ռեգգի", "Լատինա", "Բոսա նովա", "Բլյուզ", "Փանք", "Մետալ", "K-pop", "Կինեմատոգրաֆիկ", "Մանկական երգ"],
    languages: ["Русский", "English", "Հայերեն", "Deutsch", "Français", "Español", "中文", "日本語"],
    model: "Գեներացման մոդել", modelHint: "Ընտրեք որակի և արժեքի պրոֆիլը", modelTiers: { budget: "Մատչելի", balanced: "Միջին", top: "Թոփ" }, duration: "Տևողություն", durationHint: "Հասանելի վայրկյանները կախված են մոդելից", secondsUnit: "վրկ.", voiceModel: "Ձայնի մոդել", voiceModelHint: "6 պրոֆիլ՝ 2 մատչելի, 2 միջին և 2 թոփ", voice: "Ձայն", voiceHint: "Հասանելի ձայները կախված են ընտրված մոդելից", voiceFemale: "Կանացի տեմբր", voiceMale: "Տղամարդկային տեմբր", voiceFormat: "Աուդիոյի ձևաչափ", voiceFormats: ["MP3", "WAV", "Opus"], voiceOfficialNote: "Ձայների ID-ները վերցված են OpenAI Audio API-ի պաշտոնական փաստաթղթերից։ Փաստաթղթերը չեն հրապարակում սեռային պիտակներ, ուստի կանացի և տղամարդկային խմբերը ինտերֆեյսային տեմբրի դասակարգում են։", voiceDocsLabel: "Բացել TTS-ի պաշտոնական փաստաթղթերը",
    frames: "Հիմնական կադրեր", framesHint: "Ամրագրեք տեսարանի սկիզբը և ավարտը", firstFrame: "First frame", lastFrame: "Last frame", referencePhoto: "Reference photo", referencePrompt: "Լուսանկարի պրոմպտ", referencePromptPlaceholder: "Նկարագրեք, թե ինչպես օգտագործել լուսանկարը տեսարանում…", noPrompt: "պրոմպտ չկա", noFrame: "Կադր ընտրված չէ", chooseFrame: "Ընտրել", replaceFrame: "Փոխարինել",
    stylesHint: "Ընտրեք տեսարանի տեսողական լեզուն", audioStyle: "Երաժշտության ոճ", audioStylesHint: "Ընտրեք 30 երաժշտական պրոֆիլներից մեկը", audioLanguage: "Երգի լեզու", rhymePolish: "Վերջնական հանգավորում", rhymePolishOn: "ԱԲ-ն կբարելավի հանգերն ու հնչողությունը", rhymePolishOff: "Տեքստը թողնել առանց վերջնական մշակման", rhymePolishHint: "Վերջում ԱԲ-ն կհամադրի հանգերը, կհարթեցնի տողերը և երգը կդարձնի ավելի գեղեցիկ հնչող։", characters: "Կերպարներ", charactersHint: "Ամրագրեք մինչև երեք կերպար՝ կադրերի միջև կայունության համար", characterSlot: "Կերպար {n}", characterName: "Անուն", characterDescription: "Նկարագրություն և արտաքին", characterNamePlaceholder: "Օրինակ՝ Աննա", characterDescriptionPlaceholder: "Դեմք, հագուստ, տարիք, բնավորություն…", emptyCharacter: "նկարագրություն չկա", lock: "Ամրագրել", unlock: "Ապակողպել", locked: "ամրագրված է", soundStyle: "Ձայնի ոճ", lockSound: "Ամրագրել ձայնի ոճը", unlockSound: "Ապակողպել ձայնի ոճը", soundLocked: "Ձայնի ոճը ամրագրված է", language: "Գեներացման լեզու", preferencesSaved: "Տեսանյութի կարգավորումները պահպանվում են այս սարքում և ավելացվում Owner AI-ի առաջադրանքին։",
    preview: "Նախադիտում", previewEmpty: "Արդյունքը կհայտնվի գեներացման ծառայությունը միացնելուց հետո։",
    mediaUnavailable: "Մեդիայի գեներացումը դեռ միացված չէ։", generate: "Սկսել գեներացումը", prepare: "Պատրաստել առաջադրանք Owner AI-ի հետ", preparing: "Ուղարկվում է…",
    request: "Պատրաստիր առաջադրանք՝ {type} ստեղծելու համար։ Ձևաչափ՝ {format}։ Ոճ՝ {style}։ Նկարագրություն՝ {prompt}",
    editor: "Մոնտաժային սենյակ", project: "Նոր մոնտաժ", back: "Հետ", import: "Ավելացնել մեդիա", download: "Ներբեռնել նախագիծը", export: "Արտահանել տեսանյութը",
    exportUnavailable: "Պատրաստի տեսանյութի արտահանումը դեռ միացված չէ։ Կարող եք ներբեռնել նախագծի կարգավորումները։",
    tools: ["Մեդիա", "Ձևանմուշներ", "Տեքստ", "Աուդիո", "Ձայնավորում", "Ենթագրեր", "Էֆեկտներ", "Զտիչներ", "Ապրանքանիշ", "ԱԲ գործիքներ"],
    empty: "Ավելացրեք տեսանյութ, պատկեր կամ աուդիո", local: "Նախադիտումն օգտագործում է այս սարքից ընտրված ֆայլը։",
    play: "Նվագարկել", pause: "Դադար", seek: "Նվագարկման դիրք", tracks: ["Տեսանյութ", "Տեքստ", "Աուդիո"],
    inspector: "Հատկություններ", position: "Դիրք", scale: "Մասշտաբ", rotation: "Պտույտ", opacity: "Անթափանցիկություն", color: "Գույն", text: "Էկրանի տեքստ",
    trimStart: "Հատվածի սկիզբ", trimEnd: "Հատվածի ավարտ", seconds: "վ", subtitle: "Ենթագրերի տեքստ", brand: "Ապրանքանիշի ստորագրություն", filter: "Զտիչ", filters: ["Առանց զտիչի", "Սև ու սպիտակ", "Սեպիա"],
    audioNote: "Ընտրեք աուդիոֆայլ «Ավելացնել մեդիա» կոճակով՝ այն լսելու համար։", voiceNote: "Ձայնավորումը հասանելի կլինի գեներատորում՝ ծառայությունը միացնելուց հետո։",
    templatesNote: "Ընտրեք կոմպոզիցիայի ձևաչափը։", effectsNote: "Կարգավորեք մասշտաբը, պտույտը և անթափանցիկությունը հատկությունների վահանակում։",
    fileError: "Ընտրեք տեսանյութ, պատկեր կամ աուդիոֆայլ։", loadError: "Ֆայլը բացել չհաջողվեց։ Փորձեք այլ ձևաչափ։", clear: "Հեռացնել մեդիան",
  },
} as const;

export function useStudioCopy() {
  const { locale } = useLocale();
  return studioCopy[locale];
}
