"use client";
import {useRef,useState} from 'react';
import {useLanguage} from '@/components/language-provider';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Button} from '@/components/ui/button';
import {auditQuestions} from '@/data/business-os';
export function BusinessAudit({industry,onApply}:{industry:string;onApply:(summary:string)=>void}){
 const {t}=useLanguage();const [step,setStep]=useState(0);const [answers,setAnswers]=useState<(number|null)[]>(Array(8).fill(null));const [complete,setComplete]=useState(false);const heading=useRef<HTMLHeadingElement>(null);
 const q=auditQuestions[step];const selected=answers[step];
 function move(next:number){setStep(next);requestAnimationFrame(()=>heading.current?.focus());}
 function result(){setComplete(true);requestAnimationFrame(()=>heading.current?.focus());}
 function apply(){onApply(`${t('Сфера бизнеса')}: ${t(industry)}\nAI Business Audit — ${t('Предварительная карта по вашим ответам')}\n${auditQuestions.map((x,i)=>`${t(x.title)} ${t(x.options[answers[i]!] )}`).join('\n')}`);}
 return <section id="audit" className="section container os-audit"><span className="eyebrow">07 / AI BUSINESS AUDIT</span><div className="os-section-heading"><h2>{t('Покажите процесс.')}<br/><span className="lime-text">{t('Найдём точки автоматизации.')}</span></h2><p>{t('8 вопросов → предварительная карта. Без регистрации. Ответы остаются на странице до отправки формы.')}</p></div><div className="audit-shell"><div className="audit-side"><span>AUTOMATION MAP</span><p>{t("Сфера бизнеса")}: {t(industry)} <a className="text-link" href="#industries">{t("Выбрать отрасль")} ↗</a></p><ol>{auditQuestions.map((x,i)=><li key={x.area} className={answers[i]!==null?'answered':''}><span>{answers[i]!==null?'✓':String(i+1).padStart(2,'0')}</span>{t(x.area)}</li>)}</ol><p>{t('Предварительная диагностика по правилам, не AI-анализ ваших систем. Выводы проверим на аудите.')}</p></div><div className="audit-workspace">{!complete?<><div className="audit-progress"><span>{t('Вопрос')} {step+1} / 8</span><progress aria-label={t('Прогресс аудита')} max={8} value={answers.filter(x=>x!==null).length}/></div><h3 tabIndex={-1} ref={heading} id="audit-question">{t(q.title)}</h3><RadioGroup key={step} aria-labelledby="audit-question" value={selected===null?'':String(selected)} onValueChange={value=>setAnswers(old=>old.map((x,i)=>i===step?Number(value):x))} className="audit-options">{q.options.map((x,i)=><label key={x} htmlFor={`audit-${step}-${i}`} className={selected===i?'chosen':''}><RadioGroupItem id={`audit-${step}-${i}`} value={String(i)}/><span>{t(x)}</span></label>)}</RadioGroup><div className="audit-actions"><Button className="button button-outline" disabled={step===0} onClick={()=>move(step-1)}>{t('Назад')}</Button><Button className="button button-primary" disabled={selected===null} onClick={()=>step===7?result():move(step+1)}>{t(step===7?'Показать карту':'Далее')} ↗</Button></div></>:<><span className="eyebrow">AUTOMATION MAP</span><h3 ref={heading} tabIndex={-1}>{t('Предварительная карта по вашим ответам')}</h3><div className="audit-results">{auditQuestions.map((x,i)=>{const risk=x.risk[answers[i]!];return <div key={x.area}><span>{t(x.area)}</span><strong className={risk?'risk':''}>{t(risk===null?'Нужно уточнить':risk?'Проверить ручную работу':'По ответу: без разрыва')}</strong><small>{t(x.options[answers[i]!])}</small></div>;})}</div><p className="audit-result-note">{t('Это направления проверки, а не оценка эффективности. Интеграции, качество данных и возможности AI требуют отдельного разбора.')}</p><div className="audit-actions"><Button className="button button-outline" onClick={()=>{setComplete(false);move(0);}}>{t('Изменить ответы')}</Button><a className="button button-primary os-cta" href="#contact" onClick={apply}>{t('Получить подробный аудит')} ↗</a></div></>}</div></div></section>;
}
