"use client";
import { useState } from 'react';
import { useLanguage } from '@/components/language-provider';
import { layers, automationActions, automationRules, intelligence } from '@/data/business-os';
export function GrowthSystem(){
 const {t,locale}=useLanguage();const [layer,setLayer]=useState(0);
 return <section id="growth-os" className="section container os-architecture"><span className="eyebrow">01 / GROWTH OS</span><h2>{t('Всё связано. Всё под контролем.')}</h2><div className="architecture-layout"><div className="architecture-stack" role="group" aria-label={t('Слои системы')}>{layers.map((x,i)=><button key={x.code} onClick={()=>setLayer(i)} onPointerEnter={e=>{if(e.pointerType==='mouse')setLayer(i);}} onFocus={()=>setLayer(i)} aria-pressed={layer===i} aria-controls="layer-detail"><span>0{i+1}</span><strong>{x.code}</strong><span>{t(x.title)}</span><span aria-hidden="true">↗</span></button>)}</div><div className="layer-detail" id="layer-detail" aria-live="polite"><h3>{t(layers[layer].title)}</h3><p>{t(layers[layer].text)}</p><div className="layer-tools">{layers[layer].tools}</div><a className="text-link" href={`/${locale}/audit`}>{t('Построить Growth OS')} ↗</a></div></div></section>;
}
export function AutomationSection(){const {t}=useLanguage();const [action,setAction]=useState(0),[module,setModule]=useState(0);return <section id="automation" className="section container os-automation"><span className="eyebrow">04 / AI & AUTOMATION</span><h2>{t('Что можно перестать делать вручную')}</h2><div className="automation-layout"><div className="automation-actions" role="group" aria-label={t('Действия для автоматизации')}>{automationActions.map((x,i)=><button key={x} onClick={()=>setAction(i)} aria-pressed={action===i}><span>{t(x)}</span><span>{i===action?t('Автоматически'):'↗'}</span></button>)}</div><div className="automation-recipe" aria-live="polite"><span className="eyebrow">{t('ПРИМЕР ПРАВИЛА')}</span><h3>{t(automationActions[action])}</h3><ol><li><span>01</span>{t(automationRules[action][0])}</li><li><span>02</span>{t(automationRules[action][1])}</li><li><span>03</span>{t(automationRules[action][2])}</li><li><span>04</span>{t('Результат и журнал ошибок')}</li></ol><p>{t('Документы и важные AI-решения проходят проверку человеком. Ошибки передаются ответственному.')}</p></div></div><p className="automation-principle">{t('Автоматизируем то, что действительно мешает бизнесу расти.')}</p><div className="intelligence-layer"><div><span className="eyebrow">HAYDEV INTELLIGENCE LAYER</span><p>{t('Модули, которые можно включить в вашу систему.')}</p></div><div className="intelligence-selector" role="group" aria-label="HayDev Intelligence Layer">{intelligence.map((x,i)=><button key={x.name} onClick={()=>setModule(i)} aria-pressed={module===i}>{x.name}</button>)}</div><p className="intelligence-detail" aria-live="polite">{t(intelligence[module].text)}</p></div></section>;}
