"use client";
import { useLanguage } from "@/components/language-provider";
import { useRef, useState } from "react";
import { ArrowDown, ArrowUpRight, Braces, CircleDot, Cpu, Globe2, Menu, Target, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { OrbitalScene } from "@/components/visuals/orbital-scene";
import { ErpSection } from "@/components/sections/erp-section";
import { ContactForm } from "@/components/sections/contact-form";
import { modules as baseModules, navigation as baseNavigation, scenarios as baseScenarios, services as baseServices, stages as baseStages } from "@/data/site-content";
const icons = [Cpu, Globe2, Braces, Target];
function Brand() { const { t } = useLanguage(); return <a href="#home" className="brand" aria-label={t("HayDev — на главную")}><span className="brand-mark" aria-hidden="true">h<span>↗</span></span><span>haydev<span className="brand-period">.</span></span></a>; }
function SectionLabel({ number, children }: { number: string; children: React.ReactNode }) { return <div className="section-label"><span className="section-number">{number}</span><span>{children}</span></div>; }
function ContactLink({ children, outline = false }: { children?: React.ReactNode; outline?: boolean }) { const { t } = useLanguage(); return <Button asChild className={`button ${outline ? "button-outline" : "button-primary"}`}><a href="#contact">{children ?? t("Обсудить проект")}<ArrowUpRight size={19} /></a></Button>; }

export default function HayDev() {
 const { t, localize, locale } = useLanguage();
 const { modules, navigation, scenarios, services, stages } = localize({ modules: baseModules, navigation: baseNavigation, scenarios: baseScenarios, services: baseServices, stages: baseStages });
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeModule, setActiveModule] = useState(0);
  const [serviceIndex, setServiceIndex] = useState(0);
  const [stage, setStage] = useState(0);
  const [privacy, setPrivacy] = useState(false);

  const privacyOpener = useRef<HTMLElement | null>(null);
  function openPrivacy() { privacyOpener.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setPrivacy(true); }
  return <><a href="#main" className="skip-link">{t("Перейти к содержимому")}</a>
    <header className="site-header"><div className="container header-inner"><Brand /><nav className="desktop-nav" aria-label={t("Основная навигация")}>{navigation.map(item => <a href={item.href} key={item.href}>{item.label}</a>)}</nav><div className="header-actions"><nav className="language-switch" aria-label={t("Выберите язык")}>{([{ code: "hy", label: "Հայ", name: "Հայերեն" }, { code: "ru", label: "Рус", name: "Русский" }, { code: "en", label: "Eng", name: "English" }] as const).map(language => <a key={language.code} href={`/${language.code}`} hrefLang={language.code} lang={language.code} aria-label={language.name} aria-current={locale === language.code ? "page" : undefined}>{language.label}</a>)}</nav><ContactLink /><Button className="menu-toggle" variant="ghost" aria-label={menuOpen ? t("Закрыть меню") : t("Открыть меню")} aria-expanded={menuOpen} aria-controls="mobile-menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</Button></div></div>{menuOpen && <nav id="mobile-menu" className="mobile-nav" aria-label={t("Мобильная навигация")} onKeyDown={(event) => { if (event.key === "Escape") setMenuOpen(false); }}>{navigation.map(item => <a key={item.href} href={item.href} onClick={() => setMenuOpen(false)}>{item.label}<ArrowUpRight size={18} /></a>)}<a href="#contact" onClick={() => setMenuOpen(false)}>{t("Обсудить проект")}<ArrowUpRight size={18} /></a></nav>}</header>
    <main id="main"><section className="hero" id="home" aria-labelledby="hero-heading"><div className="container hero-inner"><div className="hero-copy"><div className="hero-kicker"><span className="small-cross">+</span> {t("ЦИФРОВАЯ ОПЕРАЦИОННАЯ СИСТЕМА БИЗНЕСА")}</div><h1 id="hero-heading">{t("Ваш бизнес.")}<br />{t("На новой")}<br /><span>{t("орбите.")}</span></h1><p className="hero-description">{t("Сайт привлекает. CRM ведёт продажи.")}<br className="desktop-break" /> {t("ERP управляет процессами, AI снимает рутину.")}<br className="desktop-break" /> {t("Реклама и аналитика связывают всё с результатом.")}</p><div className="hero-cta"><ContactLink /><a className="text-link" href="#erp">{t("Исследовать систему")} <ArrowDown size={17} /></a></div><p className="hero-footnote"><span className="short-line" /> {t("От первой идеи до работающей системы")}</p></div>
    <div className="hero-scene"><OrbitalScene active={activeModule}/><div className="scene-topline"><span>{t("HAYDEV / GROWTH CORE")}</span><span>01—04</span></div><div className="orbital-controls" aria-label={t("Элементы системы роста")}>{modules.map((item, index) => { const Icon = icons[index]; return <button key={item.code} className={`orbit-chip orbit-chip-${index} ${activeModule === index ? "is-active" : ""}`} aria-pressed={activeModule === index} aria-controls="module-description" onClick={() => setActiveModule(index)}><Icon size={17} /><span>{item.name}</span><span className="chip-dot" /></button>; })}</div><div className="scene-caption" id="module-description" aria-live="polite"><span className="scene-caption-code">{modules[activeModule].code}</span><p>{modules[activeModule].detail}</p></div><div className="scene-bottomline"><span><CircleDot size={13} /> {t("ЕДИНАЯ СИСТЕМА РОСТА")}</span><span>{t("ВЫБЕРИТЕ МОДУЛЬ ↑")}</span></div></div></div><div className="capability-strip"><div className="container">{[t("ИИ-АВТОМАТИЗАЦИЯ"), t("ВЕБ-РАЗРАБОТКА"), t("ERP-СИСТЕМЫ"), t("МАРКЕТИНГ"), t("CRM И ИНТЕГРАЦИИ")].map(label => <span key={label}><span className="small-cross">+</span>{label}</span>)}</div></div></section>

    <ErpSection />
    <section className="section container compact-services" id="services" aria-labelledby="services-heading"><SectionLabel number="02">{t("ЧТО МЫ СОБИРАЕМ")}</SectionLabel><h2 id="services-heading">{t("Разные задачи.")} <span className="muted-heading">{t("Система — одна.")}</span></h2><div className="service-selector" role="group" aria-label={t("Решения")}>{services.map((item,i)=><button key={item.english} aria-pressed={serviceIndex===i} aria-controls="service-detail" onClick={()=>setServiceIndex(i)}>{item.title}</button>)}</div><div id="service-detail" className="compact-service-detail" aria-live="polite"><div><span className="eyebrow">0{serviceIndex+1} / {services[serviceIndex].english}</span><h3>{services[serviceIndex].intro}</h3><p>{services[serviceIndex].text}</p></div><div><p className="lime-text">{services[serviceIndex].outcome}</p><ContactLink/></div></div></section>

    <section className="section container compact-process" id="process" aria-labelledby="process-heading"><SectionLabel number="03">{t("ТРАЕКТОРИЯ ПРОЕКТА")}</SectionLabel><h2 id="process-heading">{t("От точки А")} {t("до")} <span className="lime-text">{t("запуска.")}</span></h2><div className="process-steps" role="group" aria-label={t("Этапы проекта")}>{stages.map((item,i)=><button key={item.en} aria-pressed={stage===i} aria-controls="stage-details" onClick={()=>setStage(i)}><span>0{i+1}</span>{item.name}</button>)}</div><div className="compact-stage" id="stage-details" aria-live="polite"><div><h3>{stages[stage].title}</h3><p>{stages[stage].text}</p></div><div><span className="eyebrow">{t("НА ВЫХОДЕ")}</span><p>{stages[stage].deliverable}</p></div></div></section>

    <section className="container compact-extras" id="outcomes" aria-label={t("Результат")}><Accordion type="single" collapsible><AccordionItem value="outcomes"><AccordionTrigger>{t("КАК ЭТО РАБОТАЕТ В БИЗНЕСЕ")}</AccordionTrigger><AccordionContent><p className="compact-note">{t("Примеры сценариев, которые мы можем реализовать. Конкретный результат и показатели определяем на аудите.")}</p><Tabs defaultValue="scenario-0"><TabsList className="scenario-tab-list" aria-label={t("Сфера бизнеса")}>{scenarios.map((item,i)=><TabsTrigger key={item.label} value={`scenario-${i}`}>{item.label}</TabsTrigger>)}</TabsList>{scenarios.map((item,i)=><TabsContent key={item.label} value={`scenario-${i}`}><h3>{item.title}</h3><div className="before-after"><p>{item.before}</p><p>{item.after}</p></div><p className="compact-note">{item.measure}</p></TabsContent>)}</Tabs></AccordionContent></AccordionItem><AccordionItem value="trust"><AccordionTrigger>{t("ИНЖЕНЕРИЯ ДОВЕРИЯ")}</AccordionTrigger><AccordionContent><div className="compact-trust">{[["Контроль и доступы","Разделяем роли, защищаем ключи на сервере, согласуем правила работы с данными. В важных ИИ-сценариях решение остаётся за человеком."],["Архитектура под задачу","Выбираем инструменты по процессам и нагрузке. Документируем связи, чтобы систему можно было поддерживать и развивать."],["Измеримый прогресс","До старта определяем события и показатели. После запуска оцениваем реальные изменения, а не обещаем проценты без исходных данных."]].map(([title,text])=><article key={title}><h3>{t(title)}</h3><p>{t(text)}</p></article>)}</div></AccordionContent></AccordionItem></Accordion></section>

    <section className="contact-section" id="contact" aria-labelledby="contact-heading"><div className="container contact-grid"><div className="contact-copy"><SectionLabel number="06">{t("НАЧНЁМ С ВАШЕЙ ЗАДАЧИ")}</SectionLabel><h2 id="contact-heading">{t("У бизнеса есть")}<br />{t("потенциал.")}<br /><span className="lime-text">{t("Дадим ему")}<br />{t("систему.")}</span></h2><p>{t("Расскажите, где теряются время и заявки.")}<br />{t("Обсудим, что можно изменить и с чего начать.")}</p><div className="contact-next"><span className="small-cross">+</span><span>{t("Знакомство → аудит → карта решений")}</span></div></div><ContactForm onPrivacy={openPrivacy} /></div></section></main>
    <footer className="site-footer container"><div className="footer-top"><div><Brand /><p>{t("Технологии, которые управляют бизнесом вместе.")}<br />{t("На ваш бизнес.")}</p></div><div className="footer-links"><span className="eyebrow">{t("НАВИГАЦИЯ")}</span>{navigation.map(item => <a key={item.href} href={item.href}>{item.label}</a>)}</div><div className="footer-links"><span className="eyebrow">{t("НАЧАТЬ ДИАЛОГ")}</span><a href="#contact">{t("Обсудить проект")} <ArrowUpRight size={16} /></a><a href="#contact">{t("Получить аудит")} <ArrowUpRight size={16} /></a><span className="contact-placeholder">{t("Контакты и соцсети — скоро")}</span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} HayDev</span><button onClick={openPrivacy}>{t("Правовая информация")}</button><a href="#home">{t("Наверх")} <ArrowUpRight size={14} /></a></div></footer>
    <Dialog open={privacy} onOpenChange={setPrivacy}><DialogContent className="privacy-dialog" showCloseButton={false} onCloseAutoFocus={(event) => { event.preventDefault(); privacyOpener.current?.focus(); }}><DialogTitle>{t("Как используются данные")}</DialogTitle><DialogDescription>{t("Информация о форме заявки и подготовке сайта к открытому запуску.")}</DialogDescription><p>{t("Имя, электронная почта и описание задачи сохраняются для обсуждения вашего проекта. Согласие относится только к ответу на обращение, а не к рекламной рассылке.")}</p><p>{t("Не отправляйте пароли, платёжные данные или конфиденциальные документы. Сайт не использует рекламные трекеры.")}</p><p className="legal-placeholder">{t("Раздел готовится к публикации: реквизиты оператора, контакт для запросов о данных, сроки хранения и полная политика конфиденциальности должны быть добавлены владельцем до открытого запуска. Пока используйте форму только с тестовыми данными.")}</p><DialogClose asChild><Button className="button button-outline">{t("Понятно")} <X size={17} /></Button></DialogClose></DialogContent></Dialog></>;
}
