"use client";
import { useLanguage } from "@/components/language-provider";
import { useRef, useState, type PointerEvent } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, Braces, Check, ChevronRight, CircleDot, Compass, Cpu, Globe2, Layers3, Menu, MoveUpRight, Radio, ShieldCheck, Target, Workflow, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { ContactForm } from "@/components/sections/contact-form";
import { modules as baseModules, navigation as baseNavigation, scenarios as baseScenarios, services as baseServices, stages as baseStages } from "@/data/site-content";
const icons = [Cpu, Globe2, Braces, Target];
function Brand() { const { t } = useLanguage(); return <a href="#home" className="brand" aria-label={t("HayDev — на главную")}><span className="brand-mark" aria-hidden="true">h<span>↗</span></span><span>haydev<span className="brand-period">.</span></span></a>; }
function SectionLabel({ number, children }: { number: string; children: React.ReactNode }) { return <div className="section-label"><span className="section-number">{number}</span><span>{children}</span></div>; }
function ContactLink({ children, outline = false }: { children?: React.ReactNode; outline?: boolean }) { const { t } = useLanguage(); return <Button asChild className={`button ${outline ? "button-outline" : "button-primary"}`}><a href="#contact">{children ?? t("Обсудить проект")}<ArrowUpRight size={19} /></a></Button>; }

export default function HayDev() {
 const { t, localize, locale } = useLanguage();
 const { modules, navigation, scenarios, services, stages } = localize({ modules: baseModules, navigation: baseNavigation, scenarios: baseScenarios, services: baseServices, stages: baseStages });
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeModule, setActiveModule] = useState(0);
  const [connected, setConnected] = useState(false);
  const [stage, setStage] = useState(0);
  const [privacy, setPrivacy] = useState(false);
  const artRef = useRef<HTMLDivElement>(null);
  const privacyOpener = useRef<HTMLElement | null>(null);
  function openPrivacy() { privacyOpener.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setPrivacy(true); }
  function moveArt(event: PointerEvent<HTMLDivElement>) {
    if (event.pointerType !== "mouse" || matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const bounds = event.currentTarget.getBoundingClientRect();
    artRef.current?.style.setProperty("--rx", `${((event.clientY - bounds.top) / bounds.height - .5) * -4}deg`);
    artRef.current?.style.setProperty("--ry", `${((event.clientX - bounds.left) / bounds.width - .5) * 5}deg`);
  }
  return <><a href="#main" className="skip-link">{t("Перейти к содержимому")}</a>
    <header className="site-header"><div className="container header-inner"><Brand /><nav className="desktop-nav" aria-label={t("Основная навигация")}>{navigation.map(item => <a href={item.href} key={item.href}>{item.label}</a>)}</nav><div className="header-actions"><nav className="language-switch" aria-label={t("Выберите язык")}>{([{ code: "hy", label: "Հայ", name: "Հայերեն" }, { code: "ru", label: "Рус", name: "Русский" }, { code: "en", label: "Eng", name: "English" }] as const).map(language => <a key={language.code} href={`/${language.code}`} hrefLang={language.code} lang={language.code} aria-label={language.name} aria-current={locale === language.code ? "page" : undefined}>{language.label}</a>)}</nav><ContactLink /><Button className="menu-toggle" variant="ghost" aria-label={menuOpen ? t("Закрыть меню") : t("Открыть меню")} aria-expanded={menuOpen} aria-controls="mobile-menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</Button></div></div>{menuOpen && <nav id="mobile-menu" className="mobile-nav" aria-label={t("Мобильная навигация")} onKeyDown={(event) => { if (event.key === "Escape") setMenuOpen(false); }}>{navigation.map(item => <a key={item.href} href={item.href} onClick={() => setMenuOpen(false)}>{item.label}<ArrowUpRight size={18} /></a>)}<a href="#contact" onClick={() => setMenuOpen(false)}>{t("Обсудить проект")}<ArrowUpRight size={18} /></a></nav>}</header>
    <main id="main"><section className="hero" id="home" aria-labelledby="hero-heading"><div className="container hero-inner"><div className="hero-copy"><div className="hero-kicker"><span className="small-cross">+</span> {t("ЦЕНТР УПРАВЛЕНИЯ РОСТОМ")}</div><h1 id="hero-heading">{t("Ваш бизнес.")}<br />{t("На новой")}<br /><span>{t("орбите.")}</span></h1><p className="hero-description">{t("Соединяем ИИ, сайты, программы и маркетинг")}<br className="desktop-break" /> {t("в одну систему. Чтобы бизнес рос,")}<br className="desktop-break" /> {t("а ручной работы становилось меньше.")}</p><div className="hero-cta"><ContactLink /><a className="text-link" href="#system">{t("Исследовать систему")} <ArrowDown size={17} /></a></div><p className="hero-footnote"><span className="short-line" /> {t("От первой идеи до работающей системы")}</p></div>
    <div className="hero-scene" onPointerMove={moveArt} onPointerLeave={() => { artRef.current?.style.setProperty("--rx", "0deg"); artRef.current?.style.setProperty("--ry", "0deg"); }}><div className="hero-art" ref={artRef}><picture><source media="(max-width: 767px)" srcSet="/images/orbital-core-mobile.webp" /><img src="/images/orbital-core.webp" alt="" width={1536} height={1024} fetchPriority="high" /></picture></div><div className="scene-topline"><span>{t("HAYDEV / GROWTH CORE")}</span><span>01—04</span></div><div className="orbital-controls" aria-label={t("Элементы системы роста")}>{modules.map((item, index) => { const Icon = icons[index]; return <button key={item.code} className={`orbit-chip orbit-chip-${index} ${activeModule === index ? "is-active" : ""}`} aria-pressed={activeModule === index} aria-controls="module-description" onClick={() => setActiveModule(index)}><Icon size={17} /><span>{item.name}</span><span className="chip-dot" /></button>; })}</div><div className="scene-caption" id="module-description" aria-live="polite"><span className="scene-caption-code">{modules[activeModule].code}</span><p>{modules[activeModule].detail}</p></div><div className="scene-bottomline"><span><CircleDot size={13} /> {t("ЕДИНАЯ СИСТЕМА РОСТА")}</span><span>{t("ВЫБЕРИТЕ МОДУЛЬ ↑")}</span></div></div></div><div className="capability-strip"><div className="container">{[t("ИИ-АВТОМАТИЗАЦИЯ"), t("ВЕБ-РАЗРАБОТКА"), t("БИЗНЕС-ПО"), t("МАРКЕТИНГ"), t("CRM И ИНТЕГРАЦИИ")].map(label => <span key={label}><span className="small-cross">+</span>{label}</span>)}</div></div></section>

    <section className="section system-section container" id="system" aria-labelledby="system-heading"><SectionLabel number="01">{t("ОТ ХАОСА К СИСТЕМЕ")}</SectionLabel><div className="section-heading"><h2 id="system-heading">{t("Инструментов много.")}<br /><span className="muted-heading">{t("Система — одна.")}</span></h2><p>{t("Когда сайт, реклама и команда работают отдельно, бизнес теряет время и обращения. Мы соединяем точки.")}</p></div><div className={`system-panel ${connected ? "connected" : "disconnected"}`}><div className="system-panel-top"><span className="eyebrow">{t("КАРТА ВАШЕГО БИЗНЕСА")}</span><label className="system-toggle"><span>{connected ? t("Система HayDev") : t("Без системы")}</span><Switch checked={connected} onCheckedChange={setConnected} aria-label={t("Включить систему HayDev")} /></label></div><div className="system-map"><svg className="system-lines" viewBox="0 0 1000 260" preserveAspectRatio="none" aria-hidden="true"><path d="M150 72 C330 72 310 130 500 130 M150 202 C330 202 310 130 500 130 M850 72 C670 72 690 130 500 130 M850 202 C670 202 690 130 500 130" /></svg><div className="map-node node-web"><Globe2 /><div><strong>{t("Сайт")}</strong><span>{connected ? t("Каждое обращение в CRM") : t("Заявки теряются в почте")}</span></div></div><div className="map-node node-marketing"><Target /><div><strong>{t("Реклама")}</strong><span>{connected ? t("Источник сделки понятен") : t("Клики есть. А продажи?")}</span></div></div><div className="system-hub"><Workflow size={32} /><strong>{connected ? "HayDev" : t("Ваш бизнес")}</strong><span>{connected ? t("Всё связано") : t("Связей не хватает")}</span></div><div className="map-node node-team"><Layers3 /><div><strong>{t("Команда")}</strong><span>{connected ? t("Задачи и роли определены") : t("Ручной перенос данных")}</span></div></div><div className="map-node node-data"><Radio /><div><strong>{t("Аналитика")}</strong><span>{connected ? t("Одна картина по воронке") : t("Данные в разных таблицах")}</span></div></div></div><div className="system-panel-bottom" aria-live="polite"><span className="status-mark">{connected ? <Check size={16} /> : <Workflow size={16} />}</span><p>{connected ? t("Заявка → ответственный → следующий шаг → измеримый результат. Инструменты работают вместе.") : t("Знакомая картина? Включите систему — и посмотрите, как меняются связи.")}</p><span className="diagram-note">{t("СХЕМА ПРИНЦИПА РАБОТЫ")}</span></div></div></section>

    <section className="section services-section container" id="services" aria-labelledby="services-heading"><SectionLabel number="02">{t("ЧТО МЫ СОБИРАЕМ")}</SectionLabel><div className="section-heading"><h2 id="services-heading">{t("Разные задачи.")}<br /><span className="muted-heading">{t("Один сильный контур.")}</span></h2><p>{t("Можно начать с одного решения. Мы проектируем его так, чтобы следующий шаг усиливал предыдущий.")}</p></div><Accordion type="single" collapsible defaultValue="service-0" className="services-list">{services.map((service, index) => <AccordionItem value={`service-${index}`} key={service.english} className="service-item"><AccordionTrigger className="service-trigger"><span className="service-index">0{index + 1}</span><span className="service-title">{service.title}</span><span className="service-en">{service.english}</span></AccordionTrigger><AccordionContent className="service-content"><div><h3>{service.intro}</h3><p>{service.text}</p><div className="service-tags">{service.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div><div className="service-result"><span className="eyebrow">{t("ЧТО МЕНЯЕТСЯ")}</span><p>{service.outcome}</p><a href="#contact" className="text-link">{t("Обсудить задачу")} <ArrowUpRight size={17} /></a></div></AccordionContent></AccordionItem>)}</Accordion></section>

    <section className="process-section" id="process" aria-labelledby="process-heading"><div className="container section"><SectionLabel number="03">{t("ТРАЕКТОРИЯ ПРОЕКТА")}</SectionLabel><div className="section-heading"><h2 id="process-heading">{t("От точки А")}<br />{t("до")} <span className="lime-text">{t("запуска.")}</span> {t("И дальше.")}</h2><p>{t("Вы видите маршрут, понимаете каждый этап и знаете, что получите на выходе.")}</p></div><div className="mission-layout"><div className="mission-map"><svg viewBox="0 0 500 400" aria-hidden="true"><ellipse cx="250" cy="200" rx="180" ry="145" /><ellipse cx="250" cy="200" rx="135" ry="109" /><path d="M250 35 V365 M40 200 H460" /></svg><div className="mission-center"><Compass size={38} /><span>{t("МАРШРУТ ПРОЕКТА")}</span><strong>0{stage + 1}<span> / 05</span></strong></div><div className="mission-stages" role="group" aria-label={t("Этапы проекта")}>{stages.map((item, index) => <button key={item.en} className={`mission-stop stop-${index} ${stage === index ? "selected" : ""}`} onClick={() => setStage(index)} aria-pressed={stage === index} aria-controls="stage-details"><span>0{index + 1}</span>{item.name}</button>)}</div></div><div className="stage-details" id="stage-details" aria-live="polite"><span className="eyebrow">{t("ЭТАП 0")}{stage + 1} <span className="line-divider" /> {stages[stage].en}</span><h3>{stages[stage].title}</h3><p>{stages[stage].text}</p><div className="stage-deliverable"><span><Check size={16} /> {t("НА ВЫХОДЕ")}</span><p>{stages[stage].deliverable}</p></div><div className="stage-navigation"><span>0{stage + 1} <span className="muted">/ 05</span></span><Button variant="ghost" className="next-stage" onClick={() => setStage((stage + 1) % stages.length)} aria-label={stage === 4 ? t("Вернуться к первому этапу") : t("Следующий этап")}>{stage === 4 ? t("К началу") : t("Следующий этап")}<ArrowRight size={19} /></Button></div></div></div></div></section>

    <section className="section container outcomes-section" id="outcomes" aria-labelledby="outcomes-heading"><SectionLabel number="04">{t("КАК ЭТО РАБОТАЕТ В БИЗНЕСЕ")}</SectionLabel><div className="section-heading"><h2 id="outcomes-heading">{t("Меньше ручного.")}<br /><span className="muted-heading">{t("Больше управляемого.")}</span></h2><p>{t("Примеры сценариев, которые мы можем реализовать. Конкретный результат и показатели определяем на аудите.")}</p></div><Tabs defaultValue="scenario-0" className="scenario-tabs"><TabsList aria-label={t("Сфера бизнеса")} className="scenario-tab-list">{scenarios.map((scenario, index) => <TabsTrigger value={`scenario-${index}`} key={scenario.label}>{scenario.label}</TabsTrigger>)}</TabsList>{scenarios.map((scenario, index) => <TabsContent value={`scenario-${index}`} key={scenario.label} className="scenario-content"><div className="scenario-narrative"><span className="eyebrow">{t("ПРИМЕР СЦЕНАРИЯ / 0")}{index + 1}</span><h3>{scenario.title}</h3><div className="before-after"><div><span>{t("СЕЙЧАС")}</span><p>{scenario.before}</p></div><div><span className="lime-text">{t("С HAYDEV")}</span><p>{scenario.after}</p></div></div></div><div className="scenario-flow"><div className="flow-chain">{scenario.steps.map((step, i) => <div key={step}><span className="flow-number">0{i + 1}</span><strong>{step}</strong>{i < 3 ? <ChevronRight size={18} /> : <Check size={18} />}</div>)}</div><div className="measure-box"><span className="eyebrow">{t("ЧТО БУДЕМ ИЗМЕРЯТЬ")}</span><p>{scenario.measure}</p></div></div></TabsContent>)}</Tabs></section>

    <section className="section container trust-section" aria-labelledby="trust-heading"><SectionLabel number="05">{t("ИНЖЕНЕРИЯ ДОВЕРИЯ")}</SectionLabel><div className="section-heading"><h2 id="trust-heading">{t("Под капотом —")}<br /><span className="muted-heading">{t("порядок.")}</span></h2><p>{t("Технологичность — это когда система понятна, управляема и продолжает работать после запуска.")}</p></div><div className="trust-grid"><article><ShieldCheck /><h3>{t("Контроль и доступы")}</h3><p>{t("Разделяем роли, защищаем ключи на сервере, согласуем правила работы с данными. В важных ИИ-сценариях решение остаётся за человеком.")}</p></article><article><Braces /><h3>{t("Архитектура под задачу")}</h3><p>{t("Выбираем инструменты по процессам и нагрузке. Документируем связи, чтобы систему можно было поддерживать и развивать.")}</p></article><article><MoveUpRight /><h3>{t("Измеримый прогресс")}</h3><p>{t("До старта определяем события и показатели. После запуска оцениваем реальные изменения, а не обещаем проценты без исходных данных.")}</p></article></div></section>

    <section className="contact-section" id="contact" aria-labelledby="contact-heading"><div className="container contact-grid"><div className="contact-copy"><SectionLabel number="06">{t("НАЧНЁМ С ВАШЕЙ ЗАДАЧИ")}</SectionLabel><h2 id="contact-heading">{t("У бизнеса есть")}<br />{t("потенциал.")}<br /><span className="lime-text">{t("Дадим ему")}<br />{t("систему.")}</span></h2><p>{t("Расскажите, где теряются время и заявки.")}<br />{t("Обсудим, что можно изменить и с чего начать.")}</p><div className="contact-next"><span className="small-cross">+</span><span>{t("Знакомство → аудит → карта решений")}</span></div></div><ContactForm onPrivacy={openPrivacy} /></div></section></main>
    <footer className="site-footer container"><div className="footer-top"><div><Brand /><p>{t("Технологии, которые работают вместе.")}<br />{t("На ваш бизнес.")}</p></div><div className="footer-links"><span className="eyebrow">{t("НАВИГАЦИЯ")}</span>{navigation.map(item => <a key={item.href} href={item.href}>{item.label}</a>)}</div><div className="footer-links"><span className="eyebrow">{t("НАЧАТЬ ДИАЛОГ")}</span><a href="#contact">{t("Обсудить проект")} <ArrowUpRight size={16} /></a><a href="#contact">{t("Получить аудит")} <ArrowUpRight size={16} /></a><span className="contact-placeholder">{t("Контакты и соцсети — скоро")}</span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} HayDev</span><button onClick={openPrivacy}>{t("Правовая информация")}</button><a href="#home">{t("Наверх")} <ArrowUpRight size={14} /></a></div></footer>
    <Dialog open={privacy} onOpenChange={setPrivacy}><DialogContent className="privacy-dialog" showCloseButton={false} onCloseAutoFocus={(event) => { event.preventDefault(); privacyOpener.current?.focus(); }}><DialogTitle>{t("Как используются данные")}</DialogTitle><DialogDescription>{t("Информация о форме заявки и подготовке сайта к открытому запуску.")}</DialogDescription><p>{t("Имя, электронная почта и описание задачи сохраняются для обсуждения вашего проекта. Согласие относится только к ответу на обращение, а не к рекламной рассылке.")}</p><p>{t("Не отправляйте пароли, платёжные данные или конфиденциальные документы. Сайт не использует рекламные трекеры.")}</p><p className="legal-placeholder">{t("Раздел готовится к публикации: реквизиты оператора, контакт для запросов о данных, сроки хранения и полная политика конфиденциальности должны быть добавлены владельцем до открытого запуска. Пока используйте форму только с тестовыми данными.")}</p><DialogClose asChild><Button className="button button-outline">{t("Понятно")} <X size={17} /></Button></DialogClose></DialogContent></Dialog></>;
}
