/**
 * HayDevOS Automation Builder — in-memory mock data layer.
 *
 * Re-exports the foundation `mockAutomations` for back-compat and adds the
 * durable-workflow surfaces: typed Automations (8+), 15+ runs with varied
 * statuses, templates, approvals, schedules, webhooks, variables, workers,
 * plus engine settings and a few analytics rollups.
 *
 * All records are orgId: "org_haydev".
 */

import { mockAutomations } from "@/lib/mock/automations";
import type {
  Automation,
  AutomationRun,
  AutomationTemplate,
  Approval,
  Schedule,
  WebhookEndpoint,
  AutomationVariable,
  Worker,
  EngineSettings,
} from "./types";

export { mockAutomations };

const ORG = "org_haydev";
const now = Date.now();
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString();
const hoursAgo = (h: number) => new Date(now - h * 3600000).toISOString();
const minsAgo = (m: number) => new Date(now - m * 60000).toISOString();
const minsAhead = (m: number) => new Date(now + m * 60000).toISOString();

// ─────────────────────────────────────────────────────────────────────────────
// Typed automations — 8 rich records with trigger/conditions/actions
// ─────────────────────────────────────────────────────────────────────────────

export const automations: Automation[] = [
  {
    id: "au_001",
    orgId: ORG,
    name: "Route inbound leads by region",
    description: "Round-robin assignment of new EU/CIS leads with a 4h SLA.",
    trigger: { type: "lead_created", config: { source: ["web", "inbound"] } },
    conditions: [
      { id: "c1", field: "lead.region", op: "in", value: ["EU", "CIS"] },
      { id: "c2", field: "lead.value", op: "gt", value: 1000 },
    ],
    actions: [
      {
        id: "a1",
        type: "assign_lead",
        config: { strategy: "round_robin", pool: ["usr_rep1", "usr_rep2"] },
      },
      {
        id: "a2",
        type: "set_priority",
        config: { level: "P2" },
      },
      {
        id: "a3",
        type: "schedule_followup",
        config: { delayHours: 4, channel: "email" },
      },
    ],
    status: "active",
    version: 3,
    maxDepth: 3,
    dedupKey: "lead:{lead.id}",
    reentryPolicy: "block",
    runs: { total: 1284, success: 1271, failed: 13, lastRunAt: hoursAgo(1) },
    createdAt: daysAgo(45),
    updatedAt: hoursAgo(6),
  },
  {
    id: "au_002",
    orgId: ORG,
    name: "Auto-generate quote from qualified lead",
    description: "When a lead turns qualified and is worth ≥ $10K, draft a quote.",
    trigger: { type: "lead_stage_changed", config: { to: "qualified" } },
    conditions: [{ id: "c1", field: "lead.value", op: "gt", value: 10000 }],
    actions: [
      {
        id: "a1",
        type: "create_quote",
        config: { template: "tpl_standard", currency: "USD" },
        requiresApproval: true,
      },
      {
        id: "a2",
        type: "send_notification",
        config: { to: ["usr_owner"], channel: "in_app" },
      },
    ],
    status: "active",
    version: 2,
    maxDepth: 2,
    dedupKey: "lead:{lead.id}:quote",
    reentryPolicy: "block",
    runs: { total: 318, success: 312, failed: 6, lastRunAt: hoursAgo(6) },
    createdAt: daysAgo(30),
    updatedAt: daysAgo(2),
  },
  {
    id: "au_003",
    orgId: ORG,
    name: "Escalate SLA breaches to owner",
    description: "Notify the org owner when any open lead breaches response SLA.",
    trigger: { type: "schedule", config: { cron: "*/5 * * * *", timezone: "UTC" } },
    conditions: [
      { id: "c1", field: "lead.slaBreached", op: "equals", value: true },
      { id: "c2", field: "lead.stage", op: "not_equals", value: "won" },
    ],
    actions: [
      {
        id: "a1",
        type: "send_telegram",
        config: { chatId: "@haydev-owner", template: "tpl_sla" },
        requiresApproval: true,
      },
      {
        id: "a2",
        type: "add_note",
        config: { body: "SLA breach auto-escalated to owner." },
      },
    ],
    status: "active",
    version: 1,
    maxDepth: 1,
    dedupKey: "lead:{lead.id}:sla",
    reentryPolicy: "allow",
    runs: { total: 47, success: 47, failed: 0, lastRunAt: hoursAgo(2) },
    createdAt: daysAgo(20),
    updatedAt: daysAgo(8),
  },
  {
    id: "au_004",
    orgId: ORG,
    name: "Classify & extract uploaded documents",
    description: "Run DocSmart pipeline on every new PDF/image upload.",
    trigger: { type: "document_uploaded", config: { mime: ["application/pdf", "image/*"] } },
    conditions: [],
    actions: [
      {
        id: "a1",
        type: "start_document_workflow",
        config: { model: "docsmart-v2", extractFields: true, reviewThreshold: 0.85 },
      },
      {
        id: "a2",
        type: "send_notification",
        config: { to: ["usr_reviewer"], channel: "in_app" },
      },
    ],
    status: "active",
    version: 4,
    maxDepth: 2,
    dedupKey: "doc:{doc.id}",
    reentryPolicy: "block",
    runs: { total: 2941, success: 2810, failed: 131, lastRunAt: minsAgo(18) },
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
  },
  {
    id: "au_005",
    orgId: ORG,
    name: "Invoice on quote accepted",
    description: "When a quote worth ≥ $1K is accepted, draft an invoice and notify finance.",
    trigger: { type: "quote_accepted", config: {} },
    conditions: [{ id: "c1", field: "quote.total", op: "gt", value: 1000 }],
    actions: [
      {
        id: "a1",
        type: "update_field",
        config: { entity: "invoice", field: "status", value: "draft" },
      },
      {
        id: "a2",
        type: "send_email",
        config: { to: "finance@haydev.os", template: "tpl_invoice_draft" },
        requiresApproval: true,
      },
    ],
    status: "active",
    version: 2,
    maxDepth: 2,
    dedupKey: "quote:{quote.id}:invoice",
    reentryPolicy: "block",
    runs: { total: 96, success: 94, failed: 2, lastRunAt: hoursAgo(18) },
    createdAt: daysAgo(25),
    updatedAt: daysAgo(3),
  },
  {
    id: "au_006",
    orgId: ORG,
    name: "Weekly pipeline digest (Mon 9:00)",
    description: "Email a Monday-morning pipeline snapshot to owners and reps.",
    trigger: { type: "schedule", config: { cron: "0 9 * * 1", timezone: "Asia/Yerevan" } },
    conditions: [],
    actions: [
      {
        id: "a1",
        type: "send_email",
        config: {
          to: ["usr_owner", "usr_rep1", "usr_rep2"],
          template: "tpl_pipeline_digest",
        },
        requiresApproval: true,
      },
    ],
    status: "paused",
    version: 1,
    maxDepth: 1,
    dedupKey: "digest:{date}",
    reentryPolicy: "block",
    runs: { total: 12, success: 12, failed: 0, lastRunAt: daysAgo(3) },
    createdAt: daysAgo(40),
    updatedAt: daysAgo(3),
  },
  {
    id: "au_007",
    orgId: ORG,
    name: "Notify Slack on big deal won",
    description: "Celebrate any deal ≥ $100K won — posts to #wins.",
    trigger: { type: "lead_stage_changed", config: { to: "won" } },
    conditions: [{ id: "c1", field: "lead.value", op: "gt", value: 100000 }],
    actions: [
      {
        id: "a1",
        type: "send_webhook",
        config: { endpoint: "wh_slack_wins", template: "tpl_win_celebrate" },
        requiresApproval: true,
      },
    ],
    status: "active",
    version: 1,
    maxDepth: 1,
    dedupKey: "lead:{lead.id}:win",
    reentryPolicy: "block",
    runs: { total: 8, success: 8, failed: 0, lastRunAt: daysAgo(1) },
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
  },
  {
    id: "au_008",
    orgId: ORG,
    name: "Approval gate — discounts > 15%",
    description: "Block quote acceptance on high-discount deals pending owner approval.",
    trigger: { type: "quote_accepted", config: {} },
    conditions: [{ id: "c1", field: "quote.discountPct", op: "gt", value: 15 }],
    actions: [
      {
        id: "a1",
        type: "send_notification",
        config: { to: ["usr_owner"], channel: "in_app", template: "tpl_approval_request" },
      },
      {
        id: "a2",
        type: "update_field",
        config: { entity: "quote", field: "approvalRequired", value: true },
      },
    ],
    status: "active",
    version: 2,
    maxDepth: 1,
    dedupKey: "quote:{quote.id}:approval",
    reentryPolicy: "block",
    runs: { total: 23, success: 21, failed: 2, lastRunAt: daysAgo(2) },
    createdAt: daysAgo(18),
    updatedAt: daysAgo(2),
  },
  {
    id: "au_009",
    orgId: ORG,
    name: "Re-engage cold leads (no activity 14d)",
    description: "Daily sweep — enqueue a re-engage email for leads silent ≥ 14 days.",
    trigger: { type: "schedule", config: { cron: "0 10 * * *", timezone: "Asia/Yerevan" } },
    conditions: [
      { id: "c1", field: "lead.lastActivityDaysAgo", op: "gt", value: 14 },
      { id: "c2", field: "lead.stage", op: "not_equals", value: "won" },
      { id: "c3", field: "lead.stage", op: "not_equals", value: "lost" },
    ],
    actions: [
      {
        id: "a1",
        type: "send_email",
        config: { template: "tpl_reengage", ownerOnly: true },
        requiresApproval: true,
      },
      {
        id: "a2",
        type: "add_note",
        config: { body: "Cold-lead re-engagement queued." },
      },
    ],
    status: "draft",
    version: 1,
    maxDepth: 1,
    dedupKey: "lead:{lead.id}:reengage:{date}",
    reentryPolicy: "queue",
    runs: { total: 0, success: 0, failed: 0, lastRunAt: null },
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Automation runs — 15+ with varied statuses + rich step timelines
// ─────────────────────────────────────────────────────────────────────────────

export const automationRuns: AutomationRun[] = [
  {
    id: "run_001",
    orgId: ORG,
    automationId: "au_001",
    automationName: "Route inbound leads by region",
    status: "success",
    triggerSource: "lead_created · lead_ld_8842",
    startedAt: minsAgo(58),
    finishedAt: minsAgo(57),
    durationMs: 920,
    idempotencyKey: "lead:lead_ld_8842",
    causationId: "evt_lead_created_8842",
    worker: "wkr-eu-1",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Lead created (web/inbound)",
        status: "success",
        durationMs: 12,
        retries: 0,
        input: { leadId: "lead_ld_8842", source: "web" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "condition",
        label: "lead.region in [EU, CIS]",
        status: "success",
        durationMs: 4,
        retries: 0,
        input: { region: "EU" },
        output: { matched: true },
      },
      {
        id: "s3",
        kind: "action",
        label: "assign_lead (round_robin)",
        status: "success",
        durationMs: 540,
        retries: 0,
        input: { pool: ["usr_rep1", "usr_rep2"] },
        output: { assignee: "usr_rep1" },
      },
      {
        id: "s4",
        kind: "action",
        label: "schedule_followup (+4h)",
        status: "success",
        durationMs: 320,
        retries: 0,
        input: { delayHours: 4 },
        output: { scheduledFor: minsAhead(240) },
      },
    ],
    retryCount: 0,
  },
  {
    id: "run_002",
    orgId: ORG,
    automationId: "au_004",
    automationName: "Classify & extract uploaded documents",
    status: "running",
    triggerSource: "document_uploaded · doc_7781",
    startedAt: minsAgo(2),
    finishedAt: null,
    durationMs: 0,
    idempotencyKey: "doc:doc_7781",
    causationId: "evt_doc_uploaded_7781",
    worker: "wkr-eu-2",
    heartbeatAt: minsAgo(0.2),
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Document uploaded (application/pdf)",
        status: "success",
        durationMs: 9,
        retries: 0,
        input: { docId: "doc_7781", mime: "application/pdf" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "action",
        label: "start_document_workflow (docsmart-v2)",
        status: "running",
        durationMs: 0,
        retries: 0,
        input: { model: "docsmart-v2", extractFields: true },
        output: {},
      },
    ],
    retryCount: 0,
  },
  {
    id: "run_003",
    orgId: ORG,
    automationId: "au_002",
    automationName: "Auto-generate quote from qualified lead",
    status: "awaiting_approval",
    triggerSource: "lead_stage_changed · lead_ld_7100",
    startedAt: minsAgo(14),
    finishedAt: null,
    durationMs: 0,
    idempotencyKey: "lead:lead_ld_7100:quote",
    causationId: "evt_lead_stage_7100",
    worker: "wkr-eu-1",
    heartbeatAt: minsAgo(0.5),
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Lead stage changed → qualified",
        status: "success",
        durationMs: 11,
        retries: 0,
        input: { leadId: "lead_ld_7100", to: "qualified" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "condition",
        label: "lead.value > 10000",
        status: "success",
        durationMs: 5,
        retries: 0,
        input: { value: 24500 },
        output: { matched: true },
      },
      {
        id: "s3",
        kind: "action",
        label: "create_quote (approval required)",
        status: "awaiting_approval",
        durationMs: 0,
        retries: 0,
        input: { template: "tpl_standard", currency: "USD" },
        output: { approvalId: "apv_003" },
      },
    ],
    retryCount: 0,
  },
  {
    id: "run_004",
    orgId: ORG,
    automationId: "au_004",
    automationName: "Classify & extract uploaded documents",
    status: "failed",
    triggerSource: "document_uploaded · doc_7779",
    startedAt: hoursAgo(3),
    finishedAt: hoursAgo(3),
    durationMs: 4120,
    idempotencyKey: "doc:doc_7779",
    causationId: "evt_doc_uploaded_7779",
    worker: "wkr-eu-2",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Document uploaded (image/png)",
        status: "success",
        durationMs: 10,
        retries: 0,
        input: { docId: "doc_7779", mime: "image/png" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "action",
        label: "start_document_workflow (docsmart-v2)",
        status: "failed",
        durationMs: 4110,
        retries: 2,
        input: { model: "docsmart-v2" },
        output: {},
        error: "model_timeout: docsmart-v2 did not respond within 4s",
      },
    ],
    errorType: "model_timeout",
    errorMessage: "docsmart-v2 did not respond within 4s",
    retryCount: 2,
  },
  {
    id: "run_005",
    orgId: ORG,
    automationId: "au_007",
    automationName: "Notify Slack on big deal won",
    status: "success",
    triggerSource: "lead_stage_changed · lead_ld_6900",
    startedAt: hoursAgo(20),
    finishedAt: hoursAgo(20),
    durationMs: 610,
    idempotencyKey: "lead:lead_ld_6900:win",
    causationId: "evt_lead_stage_6900",
    worker: "wkr-eu-3",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Lead stage changed → won",
        status: "success",
        durationMs: 10,
        retries: 0,
        input: { leadId: "lead_ld_6900", to: "won" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "condition",
        label: "lead.value > 100000",
        status: "success",
        durationMs: 4,
        retries: 0,
        input: { value: 142000 },
        output: { matched: true },
      },
      {
        id: "s3",
        kind: "action",
        label: "send_webhook (#wins)",
        status: "success",
        durationMs: 596,
        retries: 0,
        input: { endpoint: "wh_slack_wins", template: "tpl_win_celebrate" },
        output: { delivered: true, httpStatus: 200 },
      },
    ],
    retryCount: 0,
  },
  {
    id: "run_006",
    orgId: ORG,
    automationId: "au_005",
    automationName: "Invoice on quote accepted",
    status: "success",
    triggerSource: "quote_accepted · q_4471",
    startedAt: hoursAgo(18),
    finishedAt: hoursAgo(18),
    durationMs: 1840,
    idempotencyKey: "quote:q_4471:invoice",
    causationId: "evt_quote_accepted_4471",
    worker: "wkr-eu-1",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Quote accepted",
        status: "success",
        durationMs: 9,
        retries: 0,
        input: { quoteId: "q_4471" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "condition",
        label: "quote.total > 1000",
        status: "success",
        durationMs: 4,
        retries: 0,
        input: { total: 8200 },
        output: { matched: true },
      },
      {
        id: "s3",
        kind: "action",
        label: "update_field (invoice.status = draft)",
        status: "success",
        durationMs: 410,
        retries: 0,
        input: { entity: "invoice", field: "status", value: "draft" },
        output: { invoiceId: "inv_5512" },
      },
      {
        id: "s4",
        kind: "action",
        label: "send_email (finance@haydev.os)",
        status: "success",
        durationMs: 1417,
        retries: 0,
        input: { to: "finance@haydev.os", template: "tpl_invoice_draft" },
        output: { delivered: true, messageId: "msg_8821" },
      },
    ],
    retryCount: 0,
  },
  {
    id: "run_007",
    orgId: ORG,
    automationId: "au_008",
    automationName: "Approval gate — discounts > 15%",
    status: "success",
    triggerSource: "quote_accepted · q_4460",
    startedAt: hoursAgo(28),
    finishedAt: hoursAgo(27),
    durationMs: 60000,
    idempotencyKey: "quote:q_4460:approval",
    causationId: "evt_quote_accepted_4460",
    worker: "wkr-eu-2",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Quote accepted",
        status: "success",
        durationMs: 11,
        retries: 0,
        input: { quoteId: "q_4460" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "condition",
        label: "quote.discountPct > 15",
        status: "success",
        durationMs: 5,
        retries: 0,
        input: { discountPct: 18 },
        output: { matched: true },
      },
      {
        id: "s3",
        kind: "action",
        label: "send_notification (usr_owner)",
        status: "success",
        durationMs: 380,
        retries: 0,
        input: { to: ["usr_owner"], channel: "in_app" },
        output: { notificationId: "ntf_3320" },
      },
      {
        id: "s4",
        kind: "action",
        label: "update_field (quote.approvalRequired = true)",
        status: "success",
        durationMs: 415,
        retries: 0,
        input: { entity: "quote", field: "approvalRequired", value: true },
        output: { quoteId: "q_4460" },
      },
    ],
    retryCount: 0,
  },
  {
    id: "run_008",
    orgId: ORG,
    automationId: "au_003",
    automationName: "Escalate SLA breaches to owner",
    status: "failed",
    triggerSource: "schedule · */5 * * * *",
    startedAt: hoursAgo(5),
    finishedAt: hoursAgo(5),
    durationMs: 3200,
    idempotencyKey: "lead:lead_ld_5520:sla",
    causationId: "evt_sla_breach_5520",
    worker: "wkr-eu-1",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Schedule fired (*/5 * * * *)",
        status: "success",
        durationMs: 8,
        retries: 0,
        input: { cron: "*/5 * * * *" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "condition",
        label: "lead.slaBreached equals true",
        status: "success",
        durationMs: 4,
        retries: 0,
        input: { slaBreached: true },
        output: { matched: true },
      },
      {
        id: "s3",
        kind: "action",
        label: "send_telegram (@haydev-owner)",
        status: "failed",
        durationMs: 3188,
        retries: 3,
        input: { chatId: "@haydev-owner", template: "tpl_sla" },
        output: {},
        error: "telegram_api: 401 Unauthorized — bot token revoked",
      },
    ],
    errorType: "upstream_auth",
    errorMessage: "telegram_api: 401 Unauthorized — bot token revoked",
    retryCount: 3,
  },
  {
    id: "run_009",
    orgId: ORG,
    automationId: "au_001",
    automationName: "Route inbound leads by region",
    status: "queued",
    triggerSource: "lead_created · lead_ld_9101",
    startedAt: minsAgo(0.5),
    finishedAt: null,
    durationMs: 0,
    idempotencyKey: "lead:lead_ld_9101",
    causationId: "evt_lead_created_9101",
    worker: "—",
    heartbeatAt: null,
    steps: [],
    retryCount: 0,
  },
  {
    id: "run_010",
    orgId: ORG,
    automationId: "au_004",
    automationName: "Classify & extract uploaded documents",
    status: "success",
    triggerSource: "document_uploaded · doc_7770",
    startedAt: hoursAgo(7),
    finishedAt: hoursAgo(7),
    durationMs: 2210,
    idempotencyKey: "doc:doc_7770",
    causationId: "evt_doc_uploaded_7770",
    worker: "wkr-eu-2",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Document uploaded (application/pdf)",
        status: "success",
        durationMs: 10,
        retries: 0,
        input: { docId: "doc_7770" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "action",
        label: "start_document_workflow (docsmart-v2)",
        status: "success",
        durationMs: 1810,
        retries: 1,
        input: { model: "docsmart-v2" },
        output: { classification: "invoice", confidence: 0.94 },
      },
      {
        id: "s3",
        kind: "action",
        label: "send_notification (usr_reviewer)",
        status: "success",
        durationMs: 390,
        retries: 0,
        input: { to: ["usr_reviewer"] },
        output: { notificationId: "ntf_3301" },
      },
    ],
    retryCount: 1,
  },
  {
    id: "run_011",
    orgId: ORG,
    automationId: "au_002",
    automationName: "Auto-generate quote from qualified lead",
    status: "failed",
    triggerSource: "lead_stage_changed · lead_ld_6400",
    startedAt: hoursAgo(11),
    finishedAt: hoursAgo(11),
    durationMs: 1240,
    idempotencyKey: "lead:lead_ld_6400:quote",
    causationId: "evt_lead_stage_6400",
    worker: "wkr-eu-3",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Lead stage changed → qualified",
        status: "success",
        durationMs: 11,
        retries: 0,
        input: { leadId: "lead_ld_6400" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "condition",
        label: "lead.value > 10000",
        status: "skipped",
        durationMs: 4,
        retries: 0,
        input: { value: 6800 },
        output: { matched: false },
      },
    ],
    errorType: "condition_not_met",
    errorMessage: "Conditions evaluated false — no actions executed.",
    retryCount: 0,
  },
  {
    id: "run_012",
    orgId: ORG,
    automationId: "au_007",
    automationName: "Notify Slack on big deal won",
    status: "cancelled",
    triggerSource: "lead_stage_changed · lead_ld_6210",
    startedAt: hoursAgo(40),
    finishedAt: hoursAgo(40),
    durationMs: 240,
    idempotencyKey: "lead:lead_ld_6210:win",
    causationId: "evt_lead_stage_6210",
    worker: "wkr-eu-3",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Lead stage changed → won",
        status: "success",
        durationMs: 9,
        retries: 0,
        input: { leadId: "lead_ld_6210" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "condition",
        label: "lead.value > 100000",
        status: "success",
        durationMs: 4,
        retries: 0,
        input: { value: 105000 },
        output: { matched: true },
      },
      {
        id: "s3",
        kind: "action",
        label: "send_webhook (#wins)",
        status: "failed",
        durationMs: 227,
        retries: 1,
        input: { endpoint: "wh_slack_wins" },
        output: {},
        error: "cancelled_by_operator: user aborted before retry",
      },
    ],
    errorType: "cancelled_by_operator",
    errorMessage: "Operator cancelled the run mid-flight.",
    retryCount: 1,
  },
  {
    id: "run_013",
    orgId: ORG,
    automationId: "au_005",
    automationName: "Invoice on quote accepted",
    status: "success",
    triggerSource: "quote_accepted · q_4399",
    startedAt: hoursAgo(50),
    finishedAt: hoursAgo(50),
    durationMs: 1640,
    idempotencyKey: "quote:q_4399:invoice",
    causationId: "evt_quote_accepted_4399",
    worker: "wkr-eu-2",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Quote accepted",
        status: "success",
        durationMs: 10,
        retries: 0,
        input: { quoteId: "q_4399" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "condition",
        label: "quote.total > 1000",
        status: "success",
        durationMs: 4,
        retries: 0,
        input: { total: 3200 },
        output: { matched: true },
      },
      {
        id: "s3",
        kind: "action",
        label: "update_field (invoice.status = draft)",
        status: "success",
        durationMs: 220,
        retries: 0,
        input: { entity: "invoice", field: "status", value: "draft" },
        output: { invoiceId: "inv_5502" },
      },
      {
        id: "s4",
        kind: "action",
        label: "send_email (finance@haydev.os)",
        status: "success",
        durationMs: 1406,
        retries: 0,
        input: { to: "finance@haydev.os" },
        output: { delivered: true, messageId: "msg_8802" },
      },
    ],
    retryCount: 0,
  },
  {
    id: "run_014",
    orgId: ORG,
    automationId: "au_003",
    automationName: "Escalate SLA breaches to owner",
    status: "success",
    triggerSource: "schedule · */5 * * * *",
    startedAt: hoursAgo(2),
    finishedAt: hoursAgo(2),
    durationMs: 720,
    idempotencyKey: "lead:lead_ld_5520:sla",
    causationId: "evt_sla_breach_5520_retry",
    worker: "wkr-eu-1",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Schedule fired (*/5 * * * *)",
        status: "success",
        durationMs: 8,
        retries: 0,
        input: { cron: "*/5 * * * *" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "action",
        label: "send_telegram (@haydev-owner)",
        status: "success",
        durationMs: 712,
        retries: 0,
        input: { chatId: "@haydev-owner", template: "tpl_sla" },
        output: { delivered: true, messageId: "tg_5521" },
      },
    ],
    retryCount: 0,
  },
  {
    id: "run_015",
    orgId: ORG,
    automationId: "au_008",
    automationName: "Approval gate — discounts > 15%",
    status: "failed",
    triggerSource: "quote_accepted · q_4388",
    startedAt: daysAgo(2),
    finishedAt: daysAgo(2),
    durationMs: 86400000,
    idempotencyKey: "quote:q_4388:approval",
    causationId: "evt_quote_accepted_4388",
    worker: "wkr-eu-2",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Quote accepted",
        status: "success",
        durationMs: 10,
        retries: 0,
        input: { quoteId: "q_4388" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "condition",
        label: "quote.discountPct > 15",
        status: "success",
        durationMs: 5,
        retries: 0,
        input: { discountPct: 22 },
        output: { matched: true },
      },
      {
        id: "s3",
        kind: "action",
        label: "send_notification (usr_owner)",
        status: "success",
        durationMs: 390,
        retries: 0,
        input: { to: ["usr_owner"] },
        output: { notificationId: "ntf_3312" },
      },
      {
        id: "s4",
        kind: "action",
        label: "update_field (quote.approvalRequired = true)",
        status: "failed",
        durationMs: 86390595,
        retries: 2,
        input: { entity: "quote", field: "approvalRequired", value: true },
        output: {},
        error: "approval_expired: owner did not respond within 24h",
      },
    ],
    errorType: "approval_expired",
    errorMessage: "Owner did not approve within 24h — approval expired.",
    retryCount: 2,
  },
  {
    id: "run_016",
    orgId: ORG,
    automationId: "au_001",
    automationName: "Route inbound leads by region",
    status: "success",
    triggerSource: "lead_created · lead_ld_8830",
    startedAt: hoursAgo(3.2),
    finishedAt: hoursAgo(3.2),
    durationMs: 880,
    idempotencyKey: "lead:lead_ld_8830",
    causationId: "evt_lead_created_8830",
    worker: "wkr-eu-1",
    heartbeatAt: null,
    steps: [
      {
        id: "s1",
        kind: "trigger",
        label: "Lead created (web/inbound)",
        status: "success",
        durationMs: 11,
        retries: 0,
        input: { leadId: "lead_ld_8830", source: "inbound" },
        output: { matched: true },
      },
      {
        id: "s2",
        kind: "action",
        label: "assign_lead (round_robin)",
        status: "success",
        durationMs: 510,
        retries: 0,
        input: { pool: ["usr_rep1", "usr_rep2"] },
        output: { assignee: "usr_rep2" },
      },
    ],
    retryCount: 0,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Templates — gallery
// ─────────────────────────────────────────────────────────────────────────────

export const automationTemplates: AutomationTemplate[] = [
  {
    id: "tpl_001",
    name: "Auto-assign new leads by source",
    description:
      "Round-robin assign every new lead to a regional rep based on its source channel.",
    category: "lead",
    trigger: { type: "lead_created", config: { source: ["web", "inbound", "referral"] } },
    conditions: [],
    actions: [
      { type: "assign_lead", config: { strategy: "round_robin", pool: ["usr_rep1", "usr_rep2"] } },
      { type: "schedule_followup", config: { delayHours: 4, channel: "email" } },
    ],
    installs: 482,
    rating: 4.8,
  },
  {
    id: "tpl_002",
    name: "Follow-up reminder 3 days after no response",
    description:
      "Daily sweep — if a lead has been silent for 3+ days, enqueue a follow-up task for the owner.",
    category: "lead",
    trigger: { type: "schedule", config: { cron: "0 9 * * *", timezone: "UTC" } },
    conditions: [
      { field: "lead.lastActivityDaysAgo", op: "gt", value: 3 },
      { field: "lead.stage", op: "not_equals", value: "won" },
    ],
    actions: [
      { type: "create_task", config: { title: "Follow up with {lead.name}", dueInHours: 24 } },
      { type: "send_notification", config: { channel: "in_app" } },
    ],
    installs: 318,
    rating: 4.6,
  },
  {
    id: "tpl_003",
    name: "Notify on high-value quote accepted",
    description:
      "When a quote ≥ $50K is accepted, post a win to Slack #wins and email the owner.",
    category: "quote",
    trigger: { type: "quote_accepted", config: {} },
    conditions: [{ field: "quote.total", op: "gt", value: 50000 }],
    actions: [
      {
        type: "send_webhook",
        config: { endpoint: "wh_slack_wins", template: "tpl_win_celebrate" },
        requiresApproval: true,
      },
      {
        type: "send_email",
        config: { to: "owner@haydev.os", template: "tpl_big_win" },
        requiresApproval: true,
      },
    ],
    installs: 207,
    rating: 4.7,
  },
  {
    id: "tpl_004",
    name: "Start document workflow on contract upload",
    description:
      "On any contract-classified upload, kick off the DocSmart review + AI extraction pipeline.",
    category: "document",
    trigger: { type: "document_uploaded", config: { mime: ["application/pdf"] } },
    conditions: [],
    actions: [
      {
        type: "start_document_workflow",
        config: { model: "docsmart-v2", extractFields: true, reviewThreshold: 0.85 },
      },
      { type: "send_notification", config: { to: ["usr_reviewer"], channel: "in_app" } },
    ],
    installs: 612,
    rating: 4.9,
  },
  {
    id: "tpl_005",
    name: "Daily cold-lead re-engagement",
    description:
      "Sweep leads silent ≥ 14d (not won/lost), enqueue a templated re-engage email.",
    category: "schedule",
    trigger: { type: "schedule", config: { cron: "0 10 * * *", timezone: "Asia/Yerevan" } },
    conditions: [
      { field: "lead.lastActivityDaysAgo", op: "gt", value: 14 },
      { field: "lead.stage", op: "not_equals", value: "won" },
    ],
    actions: [
      {
        type: "send_email",
        config: { template: "tpl_reengage", ownerOnly: true },
        requiresApproval: true,
      },
    ],
    installs: 144,
    rating: 4.4,
  },
  {
    id: "tpl_006",
    name: "Owner AI digest every morning",
    description:
      "Run the Owner AI agent at 8:00 to summarise overnight pipeline movement and risks.",
    category: "schedule",
    trigger: { type: "schedule", config: { cron: "0 8 * * *", timezone: "Asia/Yerevan" } },
    conditions: [],
    actions: [
      {
        type: "run_ai_agent",
        config: { agent: "owner-ai", prompt: "Summarise overnight pipeline + risks." },
        requiresApproval: true,
      },
    ],
    installs: 96,
    rating: 4.5,
  },
  {
    id: "tpl_007",
    name: "Telegram alert on SLA breach",
    description: "Notify the owner via Telegram whenever any open lead breaches SLA.",
    category: "notification",
    trigger: { type: "schedule", config: { cron: "*/5 * * * *", timezone: "UTC" } },
    conditions: [
      { field: "lead.slaBreached", op: "equals", value: true },
      { field: "lead.stage", op: "not_equals", value: "won" },
    ],
    actions: [
      {
        type: "send_telegram",
        config: { chatId: "@haydev-owner", template: "tpl_sla" },
        requiresApproval: true,
      },
    ],
    installs: 73,
    rating: 4.3,
  },
  {
    id: "tpl_008",
    name: "Auto-invoice on quote accepted",
    description:
      "When a quote ≥ $1K is accepted, draft an invoice and email finance for review.",
    category: "finance",
    trigger: { type: "quote_accepted", config: {} },
    conditions: [{ field: "quote.total", op: "gt", value: 1000 }],
    actions: [
      { type: "update_field", config: { entity: "invoice", field: "status", value: "draft" } },
      {
        type: "send_email",
        config: { to: "finance@haydev.os", template: "tpl_invoice_draft" },
        requiresApproval: true,
      },
    ],
    installs: 188,
    rating: 4.6,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Approvals — pending + recent decisions
// ─────────────────────────────────────────────────────────────────────────────

export const approvals: Approval[] = [
  {
    id: "apv_001",
    orgId: ORG,
    automationId: "au_002",
    automationName: "Auto-generate quote from qualified lead",
    runId: "run_003",
    actionType: "create_quote",
    actionLabel: "create_quote · tpl_standard · USD 24,500",
    requestedBy: "Automation engine",
    requestedAt: minsAgo(14),
    status: "pending",
    contextSnapshot: { leadId: "lead_ld_7100", value: 24500, stage: "qualified" },
  },
  {
    id: "apv_002",
    orgId: ORG,
    automationId: "au_007",
    automationName: "Notify Slack on big deal won",
    runId: "run_005",
    actionType: "send_webhook",
    actionLabel: "send_webhook · #wins · lead_ld_6900",
    requestedBy: "Automation engine",
    requestedAt: hoursAgo(20),
    status: "approved",
    decidedBy: "Aram Hayrapetyan",
    decidedAt: hoursAgo(20),
    contextSnapshot: { leadId: "lead_ld_6900", value: 142000, stage: "won" },
    notes: "Looks great — celebrate!",
  },
  {
    id: "apv_003",
    orgId: ORG,
    automationId: "au_005",
    automationName: "Invoice on quote accepted",
    runId: "run_006",
    actionType: "send_email",
    actionLabel: "send_email · finance@haydev.os · tpl_invoice_draft",
    requestedBy: "Automation engine",
    requestedAt: hoursAgo(19),
    status: "approved",
    decidedBy: "Aram Hayrapetyan",
    decidedAt: hoursAgo(18),
    contextSnapshot: { quoteId: "q_4471", total: 8200 },
  },
  {
    id: "apv_004",
    orgId: ORG,
    automationId: "au_008",
    automationName: "Approval gate — discounts > 15%",
    runId: "run_015",
    actionType: "update_field",
    actionLabel: "update_field · quote.approvalRequired = true",
    requestedBy: "Automation engine",
    requestedAt: daysAgo(3),
    status: "expired",
    contextSnapshot: { quoteId: "q_4388", discountPct: 22 },
    notes: "Expired — owner did not respond within 24h.",
  },
  {
    id: "apv_005",
    orgId: ORG,
    automationId: "au_007",
    automationName: "Notify Slack on big deal won",
    runId: "run_012",
    actionType: "send_webhook",
    actionLabel: "send_webhook · #wins · lead_ld_6210",
    requestedBy: "Automation engine",
    requestedAt: hoursAgo(40),
    status: "rejected",
    decidedBy: "Aram Hayrapetyan",
    decidedAt: hoursAgo(40),
    contextSnapshot: { leadId: "lead_ld_6210", value: 105000, stage: "won" },
    notes: "False positive — lead was a duplicate.",
  },
  {
    id: "apv_006",
    orgId: ORG,
    automationId: "au_003",
    automationName: "Escalate SLA breaches to owner",
    runId: "run_008",
    actionType: "send_telegram",
    actionLabel: "send_telegram · @haydev-owner · tpl_sla",
    requestedBy: "Automation engine",
    requestedAt: hoursAgo(5),
    status: "pending",
    contextSnapshot: { leadId: "lead_ld_5520", slaBreached: true, stage: "contacted" },
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Schedules
// ─────────────────────────────────────────────────────────────────────────────

export const schedules: Schedule[] = [
  {
    id: "sch_001",
    orgId: ORG,
    automationId: "au_003",
    automationName: "Escalate SLA breaches to owner",
    cron: "*/5 * * * *",
    timezone: "UTC",
    nextRunAt: minsAhead(3),
    lastRunAt: minsAgo(2),
    status: "active",
    lastDurationMs: 720,
  },
  {
    id: "sch_002",
    orgId: ORG,
    automationId: "au_006",
    automationName: "Weekly pipeline digest (Mon 9:00)",
    cron: "0 9 * * 1",
    timezone: "Asia/Yerevan",
    nextRunAt: minsAhead(60 * 24 * 2),
    lastRunAt: daysAgo(3),
    status: "paused",
    lastDurationMs: 1840,
  },
  {
    id: "sch_003",
    orgId: ORG,
    automationId: "au_009",
    automationName: "Re-engage cold leads (no activity 14d)",
    cron: "0 10 * * *",
    timezone: "Asia/Yerevan",
    nextRunAt: minsAhead(60 * 14),
    lastRunAt: null,
    status: "active",
    lastDurationMs: 0,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Webhooks
// ─────────────────────────────────────────────────────────────────────────────

export const webhookEndpoints: WebhookEndpoint[] = [
  {
    id: "wh_001",
    orgId: ORG,
    name: "Slack #wins",
    url: "https://hooks.slack.com/services/T0/B0/XXXX",
    signingSecretMasked: "whsec_••••••••••••4f2a",
    eventTypes: ["lead.won", "quote.accepted"],
    lastDeliveryAt: minsAgo(58),
    lastStatus: "delivered",
    deliveries24h: 4,
    successRate: 100,
  },
  {
    id: "wh_002",
    orgId: ORG,
    name: "Zapier outbound",
    url: "https://hooks.zapier.com/hooks/catch/123456/abcdef/",
    signingSecretMasked: "whsec_••••••••••••9b71",
    eventTypes: ["lead.created", "document.uploaded"],
    lastDeliveryAt: hoursAgo(2),
    lastStatus: "failed",
    deliveries24h: 47,
    successRate: 95.7,
  },
  {
    id: "wh_003",
    orgId: ORG,
    name: "Internal billing pipeline",
    url: "https://internal.haydev.os/hooks/billing",
    signingSecretMasked: "whsec_••••••••••••c0d3",
    eventTypes: ["invoice.created", "payment.received"],
    lastDeliveryAt: minsAgo(12),
    lastStatus: "delivered",
    deliveries24h: 23,
    successRate: 100,
  },
  {
    id: "wh_004",
    orgId: ORG,
    name: "Partner webhook — Acme",
    url: "https://api.acme.partner/haydev/events",
    signingSecretMasked: "whsec_••••••••••••77ee",
    eventTypes: ["lead.created"],
    lastDeliveryAt: null,
    lastStatus: null,
    deliveries24h: 0,
    successRate: 0,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Variables
// ─────────────────────────────────────────────────────────────────────────────

export const automationVariables: AutomationVariable[] = [
  {
    id: "var_001",
    orgId: ORG,
    key: "OWNER_EMAIL",
    value: "owner@haydev.os",
    isSecret: false,
    scope: "org",
    updatedAt: daysAgo(30),
  },
  {
    id: "var_002",
    orgId: ORG,
    key: "FINANCE_EMAIL",
    value: "finance@haydev.os",
    isSecret: false,
    scope: "org",
    updatedAt: daysAgo(15),
  },
  {
    id: "var_003",
    orgId: ORG,
    key: "SLACK_WINS_WEBHOOK",
    value: "https://hooks.slack.com/services/T0/B0/XXXX",
    isSecret: true,
    scope: "org",
    updatedAt: daysAgo(8),
  },
  {
    id: "var_004",
    orgId: ORG,
    key: "STRIPE_SECRET_KEY",
    value: "sk_live_••••••••••••••••••••",
    isSecret: true,
    scope: "org",
    updatedAt: daysAgo(60),
  },
  {
    id: "var_005",
    orgId: ORG,
    key: "TELEGRAM_BOT_TOKEN",
    value: "•••••••••••••••••••••••••••",
    isSecret: true,
    scope: "org",
    updatedAt: daysAgo(20),
  },
  {
    id: "var_006",
    orgId: ORG,
    key: "DEFAULT_CURRENCY",
    value: "USD",
    isSecret: false,
    scope: "org",
    updatedAt: daysAgo(90),
  },
  {
    id: "var_007",
    orgId: ORG,
    key: "HIGH_VALUE_THRESHOLD",
    value: "100000",
    isSecret: false,
    scope: "org",
    updatedAt: daysAgo(10),
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Workers
// ─────────────────────────────────────────────────────────────────────────────

export const workers: Worker[] = [
  {
    id: "wkr-eu-1",
    name: "wkr-eu-1",
    status: "online",
    currentJob: "run_003",
    queueDepth: 2,
    heartbeatAt: minsAgo(0.1),
    region: "eu-central",
    jobsProcessed: 18204,
    cpuPct: 41,
  },
  {
    id: "wkr-eu-2",
    name: "wkr-eu-2",
    status: "online",
    currentJob: "run_002",
    queueDepth: 0,
    heartbeatAt: minsAgo(0.2),
    region: "eu-central",
    jobsProcessed: 22110,
    cpuPct: 67,
  },
  {
    id: "wkr-eu-3",
    name: "wkr-eu-3",
    status: "online",
    currentJob: null,
    queueDepth: 0,
    heartbeatAt: minsAgo(0.4),
    region: "eu-central",
    jobsProcessed: 9455,
    cpuPct: 12,
  },
  {
    id: "wkr-us-1",
    name: "wkr-us-1",
    status: "online",
    currentJob: null,
    queueDepth: 1,
    heartbeatAt: minsAgo(0.3),
    region: "us-east",
    jobsProcessed: 7842,
    cpuPct: 22,
  },
  {
    id: "wkr-us-2",
    name: "wkr-us-2",
    status: "draining",
    currentJob: "run_010",
    queueDepth: 3,
    heartbeatAt: minsAgo(0.5),
    region: "us-east",
    jobsProcessed: 5021,
    cpuPct: 88,
  },
  {
    id: "wkr-asia-1",
    name: "wkr-asia-1",
    status: "offline",
    currentJob: null,
    queueDepth: 0,
    heartbeatAt: hoursAgo(2),
    region: "ap-southeast",
    jobsProcessed: 0,
    cpuPct: 0,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Engine settings
// ─────────────────────────────────────────────────────────────────────────────

export const engineSettings: EngineSettings = {
  loopProtection: {
    maxDepth: 5,
    reentryPolicy: "block",
    dedupTtlSec: 3600,
  },
  retryPolicy: {
    maxRetries: 3,
    backoffStrategy: "exponential",
    initialDelayMs: 500,
    maxDelayMs: 30000,
  },
  concurrency: {
    maxConcurrentRuns: 50,
    perAutomationLimit: 5,
    queueTimeoutMs: 60000,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Analytics rollups (used by AnalyticsView)
// ─────────────────────────────────────────────────────────────────────────────

export const executionsTimeSeries = [
  { day: "Mon", success: 184, failed: 6, awaiting: 2 },
  { day: "Tue", success: 221, failed: 11, awaiting: 4 },
  { day: "Wed", success: 198, failed: 4, awaiting: 1 },
  { day: "Thu", success: 246, failed: 9, awaiting: 3 },
  { day: "Fri", success: 312, failed: 14, awaiting: 5 },
  { day: "Sat", success: 88, failed: 2, awaiting: 0 },
  { day: "Sun", success: 64, failed: 1, awaiting: 0 },
];

export const topAutomationsByRuns = [
  { name: "Classify & extract documents", runs: 2941 },
  { name: "Route inbound leads by region", runs: 1284 },
  { name: "Notify Slack on big deal won", runs: 96 },
  { name: "Invoice on quote accepted", runs: 96 },
  { name: "Auto-generate quote (qualified)", runs: 318 },
];

export const failureReasons = [
  { reason: "Upstream auth/token revoked", count: 18 },
  { reason: "Model timeout", count: 12 },
  { reason: "Approval expired", count: 9 },
  { reason: "Condition not met", count: 6 },
  { reason: "Webhook delivery failed", count: 5 },
  { reason: "Cancelled by operator", count: 4 },
];

export const approvalWaitBuckets = [
  { bucket: "<5m", count: 12 },
  { bucket: "5–30m", count: 18 },
  { bucket: "30m–2h", count: 9 },
  { bucket: "2–8h", count: 4 },
  { bucket: ">8h", count: 2 },
];

// ─────────────────────────────────────────────────────────────────────────────
// Convenience helpers
// ─────────────────────────────────────────────────────────────────────────────

export function getAutomation(id: string): Automation | undefined {
  return automations.find((a) => a.id === id);
}

export function getRun(id: string): AutomationRun | undefined {
  return automationRuns.find((r) => r.id === id);
}
