SELECT
  (SELECT COUNT(*) FROM public."Customer") AS customers,
  (SELECT COUNT(*) FROM public."Product") AS products,
  (SELECT COUNT(*) FROM public."Order") AS orders,
  (SELECT COUNT(*) FROM public."OrderItem") AS order_items,
  (SELECT COUNT(*) FROM public."Warehouse") AS warehouses,
  (SELECT COUNT(*) FROM public."InventoryBalance") AS inventory_balances,
  (SELECT COUNT(*) FROM public."InventoryMovement") AS inventory_movements,
  (SELECT COUNT(*) FROM public."InventoryReservation") AS reservations,
  (SELECT COUNT(*) FROM public."InventoryTransfer") AS transfers,
  (SELECT COUNT(*) FROM public."Fulfillment") AS fulfillments,
  (SELECT COUNT(*) FROM public."Payment") AS payments,
  (SELECT COUNT(*) FROM public."FinanceEvent") AS finance_events,
  (SELECT COUNT(*) FROM public."ERPEvent") AS erp_events,
  (SELECT COUNT(*) FROM public._prisma_migrations WHERE migration_name='20260925150000_erp_production_domain' AND finished_at IS NOT NULL AND rolled_back_at IS NULL AND checksum='60e2f49b41827a9d8ab89361023c4807fe78428c7d1db9baf7f09bdfae3cf678') AS gate6_ledger_match,
  (SELECT COUNT(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('OrderItem','OrderNumberCounter','OrderStatusEvent','Warehouse','InventoryBalance','InventoryMovement','InventoryReservation','InventoryTransfer','Fulfillment','FulfillmentItem','FinanceEvent','ERPEvent') AND c.relrowsecurity) AS erp_new_rls_tables,
  (SELECT COUNT(*) FROM information_schema.role_table_grants WHERE table_schema='public' AND grantee IN ('anon','authenticated') AND table_name IN ('Customer','Product','Order','OrderItem','OrderNumberCounter','OrderStatusEvent','Warehouse','InventoryBalance','InventoryMovement','InventoryReservation','InventoryTransfer','Fulfillment','FulfillmentItem','Invoice','Payment','FinanceEvent','ERPEvent')) AS browser_erp_grants,
  (SELECT COUNT(*) FROM pg_constraint WHERE connamespace='public'::regnamespace AND conname IN ('Order_customerId_orgId_fkey','Order_sourceQuoteVersionId_sourceQuoteId_orgId_fkey','OrderItem_orderId_orgId_fkey','OrderItem_productId_orgId_fkey','InventoryBalance_warehouseId_orgId_fkey','InventoryBalance_productId_orgId_fkey','InventoryReservation_orderItemId_orderId_orgId_fkey','Payment_orderId_orgId_fkey','FinanceEvent_paymentId_orgId_fkey')) AS essential_tenant_fks,
  (SELECT COUNT(*) FROM pg_trigger WHERE NOT tgisinternal AND tgname IN ('Order_runtime_protected','OrderItem_runtime_immutable','OrderStatusEvent_runtime_immutable','InventoryMovement_runtime_immutable','InventoryTransfer_runtime_immutable','Fulfillment_runtime_immutable','FulfillmentItem_runtime_immutable','FinanceEvent_runtime_immutable','Payment_runtime_protected','ERPEvent_runtime_protected')) AS erp_history_triggers,
  (SELECT COUNT(*) FROM pg_constraint WHERE connamespace='public'::regnamespace AND conname IN ('Order_status_check','Order_money_check','Order_quote_source_check','InventoryBalance_values_check','InventoryMovement_values_check','InventoryReservation_values_check','InventoryTransfer_values_check','Payment_status_check','Payment_parent_check','FinanceEvent_values_check')) AS essential_erp_checks,
  (SELECT COUNT(*) FROM information_schema.routine_privileges WHERE specific_schema='public' AND grantee='PUBLIC' AND routine_name IN ('haydev_protect_order','haydev_protect_payment','haydev_protect_erp_event')) AS public_guard_function_execute,
  (SELECT COUNT(*) FROM pg_constraint WHERE connamespace='public'::regnamespace AND conname='DocumentRecord_source_type_check' AND pg_get_constraintdef(oid) LIKE '%ORDER%') AS document_order_source_enabled,
  (SELECT rolsuper OR rolcreatedb OR rolcreaterole OR rolbypassrls FROM pg_roles WHERE rolname='haydev_runtime') AS runtime_has_elevated_privilege;
